image_width: 1920
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1032.57390613,    0.     ,  946.52567841,
            0.     , 1034.61733446,  613.29463012,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.03372804, -0.00759129,  0.00588024, -0.00270408, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 763.077,    0.     ,  965.311,    0.     ,
            0.     , 1007.366,  547.920,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
