(cl:in-package microstrain_inertial_msgs-msg)
(cl:export '(FILTER_CONDITION-VAL
          FILTER_CONDITION
          ROLL_PITCH_WARNING-VAL
          ROLL_PITCH_WARNING
          HEADING_WARNING-VAL
          HEADING_WARNING
          POSITION_WARNING-VAL
          POSITION_WARNING
          VELOCITY_WARNING-VAL
          VELOCITY_WARNING
          IMU_BIAS_WARNING-VAL
          IMU_BIAS_WARNING
          GNSS_CLK_WARNING-VAL
          GNSS_CLK_WARNING
          ANTENNA_LEVER_ARM_WARNING-VAL
          ANTENNA_LEVER_ARM_WARNING
          MOUNTING_TRANSFORM_WARNING-VAL
          MOUNTING_TRANSFORM_WARNING
          TIME_SYNC_WARNING-VAL
          TIME_SYNC_WARNING
          SOLUTION_ERROR-VAL
          SOLUTION_ERROR
))