(cl:in-package microstrain_inertial_msgs-msg)
(cl:export '(ANTENNA_LOCATION_RECEIVED-VAL
          ANTENNA_LOCATION_RECEIVED
          ANTENNA_DESCRIPTION_RECEIVED-VAL
          ANTENNA_DESCRIPTION_RECEIVED
          GPS_RECEIVED-VAL
          GPS_RECEIVED
          GALILEO_RECEIVED-VAL
          GALILEO_RECEIVED
          GLONASS_RECEIVED-VAL
          GLONASS_RECEIVED
          BEIDOU_RECEIVED-VAL
          BEIDOU_RECEIVED
          USING_GPS_MSM_MESSAGES-VAL
          USING_GPS_MSM_MESSAGES
          USING_GLONASS_MSM_MESSAGES-VAL
          USING_GLONASS_MSM_MESSAGES
          DONGLE_STATUS_READ_FAILED-VAL
          DONGLE_STATUS_READ_FAILED
))