(cl:in-package microstrain_inertial_msgs-msg)
(cl:export '(TIGHT_COUPLING-VAL
          TIGHT_COUPLING
          DIFFERENTIAL-VAL
          DIFFERENTIAL
          INTEGER_FIX-VAL
          INTEGER_FIX
          GPS_L1-VAL
          GPS_L1
          GPS_L2-VAL
          GPS_L2
          GPS_L5-VAL
          GPS_L5
          GLO_L1-VAL
          GLO_L1
          GLO_L2-VAL
          GLO_L2
          GAL_E1-VAL
          GAL_E1
          GAL_E5-VAL
          GAL_E5
          GAL_E6-VAL
          GAL_E6
          BEI_B1-VAL
          BEI_B1
          BEI_B2-VAL
          BEI_B2
          BEI_B3-VAL
          BEI_B3
          NO_FIX-VAL
          NO_FIX
          CONFIG_ERROR-VAL
          CONFIG_ERROR
))