(cl:in-package microstrain_inertial_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_OF_WEEK-VAL
          TIME_OF_WEEK
          WEEK_NUMBER-VAL
          WEEK_NUMBER
          EPOCH_STATUS-VAL
          EPOCH_STATUS
          DONGLE_STATUS-VAL
          DONGLE_STATUS
          GPS_CORRECTION_LATENCY-VAL
          GPS_CORRECTION_LATENCY
          GLONASS_CORRECTION_LATENCY-VAL
          GLONASS_CORRECTION_LATENCY
          GALILEO_CORRECTION_LATENCY-VAL
          GALILEO_CORRECTION_LATENCY
          BEIDOU_CORRECTION_LATENCY-VAL
          BEIDOU_CORRECTION_LATENCY
))