
(cl:in-package :asdf)

(defsystem "microstrain_inertial_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "HumanReadableStatus" :depends-on ("_package_HumanReadableStatus"))
    (:file "_package_HumanReadableStatus" :depends-on ("_package"))
    (:file "MipBaseDeviceInfo" :depends-on ("_package_MipBaseDeviceInfo"))
    (:file "_package_MipBaseDeviceInfo" :depends-on ("_package"))
    (:file "MipFilterAidingMeasurementSummary" :depends-on ("_package_MipFilterAidingMeasurementSummary"))
    (:file "_package_MipFilterAidingMeasurementSummary" :depends-on ("_package"))
    (:file "MipFilterAidingMeasurementSummaryIndicator" :depends-on ("_package_MipFilterAidingMeasurementSummaryIndicator"))
    (:file "_package_MipFilterAidingMeasurementSummaryIndicator" :depends-on ("_package"))
    (:file "MipFilterGnssDualAntennaStatus" :depends-on ("_package_MipFilterGnssDualAntennaStatus"))
    (:file "_package_MipFilterGnssDualAntennaStatus" :depends-on ("_package"))
    (:file "MipFilterGnssDualAntennaStatusStatusFlags" :depends-on ("_package_MipFilterGnssDualAntennaStatusStatusFlags"))
    (:file "_package_MipFilterGnssDualAntennaStatusStatusFlags" :depends-on ("_package"))
    (:file "MipFilterGnssPositionAidingStatus" :depends-on ("_package_MipFilterGnssPositionAidingStatus"))
    (:file "_package_MipFilterGnssPositionAidingStatus" :depends-on ("_package"))
    (:file "MipFilterGnssPositionAidingStatusStatus" :depends-on ("_package_MipFilterGnssPositionAidingStatusStatus"))
    (:file "_package_MipFilterGnssPositionAidingStatusStatus" :depends-on ("_package"))
    (:file "MipFilterMultiAntennaOffsetCorrection" :depends-on ("_package_MipFilterMultiAntennaOffsetCorrection"))
    (:file "_package_MipFilterMultiAntennaOffsetCorrection" :depends-on ("_package"))
    (:file "MipFilterStatus" :depends-on ("_package_MipFilterStatus"))
    (:file "_package_MipFilterStatus" :depends-on ("_package"))
    (:file "MipFilterStatusGq7StatusFlags" :depends-on ("_package_MipFilterStatusGq7StatusFlags"))
    (:file "_package_MipFilterStatusGq7StatusFlags" :depends-on ("_package"))
    (:file "MipFilterStatusGx5StatusFlags" :depends-on ("_package_MipFilterStatusGx5StatusFlags"))
    (:file "_package_MipFilterStatusGx5StatusFlags" :depends-on ("_package"))
    (:file "MipGnssCorrectionsRtkCorrectionsStatus" :depends-on ("_package_MipGnssCorrectionsRtkCorrectionsStatus"))
    (:file "_package_MipGnssCorrectionsRtkCorrectionsStatus" :depends-on ("_package"))
    (:file "MipGnssCorrectionsRtkCorrectionsStatusDongleStatus" :depends-on ("_package_MipGnssCorrectionsRtkCorrectionsStatusDongleStatus"))
    (:file "_package_MipGnssCorrectionsRtkCorrectionsStatusDongleStatus" :depends-on ("_package"))
    (:file "MipGnssCorrectionsRtkCorrectionsStatusEpochStatus" :depends-on ("_package_MipGnssCorrectionsRtkCorrectionsStatusEpochStatus"))
    (:file "_package_MipGnssCorrectionsRtkCorrectionsStatusEpochStatus" :depends-on ("_package"))
    (:file "MipGnssFixInfo" :depends-on ("_package_MipGnssFixInfo"))
    (:file "_package_MipGnssFixInfo" :depends-on ("_package"))
    (:file "MipGnssFixInfoFixFlags" :depends-on ("_package_MipGnssFixInfoFixFlags"))
    (:file "_package_MipGnssFixInfoFixFlags" :depends-on ("_package"))
    (:file "MipGnssRfErrorDetection" :depends-on ("_package_MipGnssRfErrorDetection"))
    (:file "_package_MipGnssRfErrorDetection" :depends-on ("_package"))
    (:file "MipGnssSbasInfo" :depends-on ("_package_MipGnssSbasInfo"))
    (:file "_package_MipGnssSbasInfo" :depends-on ("_package"))
    (:file "MipGnssSbasInfoSbasStatus" :depends-on ("_package_MipGnssSbasInfoSbasStatus"))
    (:file "_package_MipGnssSbasInfoSbasStatus" :depends-on ("_package"))
    (:file "MipGpsTimestamp" :depends-on ("_package_MipGpsTimestamp"))
    (:file "_package_MipGpsTimestamp" :depends-on ("_package"))
    (:file "MipGpsTimestampValidFlags" :depends-on ("_package_MipGpsTimestampValidFlags"))
    (:file "_package_MipGpsTimestampValidFlags" :depends-on ("_package"))
    (:file "MipHeader" :depends-on ("_package_MipHeader"))
    (:file "_package_MipHeader" :depends-on ("_package"))
    (:file "MipSensorOverrangeStatus" :depends-on ("_package_MipSensorOverrangeStatus"))
    (:file "_package_MipSensorOverrangeStatus" :depends-on ("_package"))
    (:file "MipSensorOverrangeStatusStatus" :depends-on ("_package_MipSensorOverrangeStatusStatus"))
    (:file "_package_MipSensorOverrangeStatusStatus" :depends-on ("_package"))
    (:file "MipSensorTemperatureStatistics" :depends-on ("_package_MipSensorTemperatureStatistics"))
    (:file "_package_MipSensorTemperatureStatistics" :depends-on ("_package"))
    (:file "MipSystemBuiltInTest" :depends-on ("_package_MipSystemBuiltInTest"))
    (:file "_package_MipSystemBuiltInTest" :depends-on ("_package"))
    (:file "MipSystemTimeSyncStatus" :depends-on ("_package_MipSystemTimeSyncStatus"))
    (:file "_package_MipSystemTimeSyncStatus" :depends-on ("_package"))
  ))