<?xml version="1.0"?>
<package format="3">
  <name>gstreamer_nvjpegenc_node</name>
  <version>0.1.0</version>
  <description>Multi-camera JPEG compression publisher using GStreamer and nvjpeg</description>

  <maintainer email="mapping@yourdomain.com">Mapping User</maintainer>
  <license>MIT</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build dependencies -->
 <build_depend>rclcpp</build_depend>
 <build_depend>sensor_msgs</build_depend>
 <build_depend>yaml-cpp</build_depend>
 <build_depend>opencv</build_depend>


  <!-- Run-time dependencies -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>yaml-cpp</exec_depend>

  <!-- Export information -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

