<?xml version="1.0"?>
<package format="2">
  <name>gstreamer_camera_wrapper</name>
  <version>0.0.1</version>
  <description>GStreamer-based H264 camera publisher</description>

  <maintainer email="you@example.com">your_name</maintainer>
  <license>MIT</license>

  <!-- build system -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- build deps -->
  <build_depend>roscpp</build_depend>
  <build_depend>sensor_msgs</build_depend>

  <!-- run deps -->
  <exec_depend>roscpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <!-- yaml-cpp는 system dependency -->
  <depend>yaml-cpp</depend>

</package>

