// Generated by gencpp from file ouster_ros/Telemetry.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_TELEMETRY_H
#define OUSTER_ROS_MESSAGE_TELEMETRY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ouster_ros
{
template <class ContainerAllocator>
struct Telemetry_
{
  typedef Telemetry_<ContainerAllocator> Type;

  Telemetry_()
    : header()
    , countdown_thermal_shutdown(0)
    , countdown_shot_limiting(0)
    , thermal_shutdown(0)
    , shot_limiting(0)  {
    }
  Telemetry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , countdown_thermal_shutdown(0)
    , countdown_shot_limiting(0)
    , thermal_shutdown(0)
    , shot_limiting(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _countdown_thermal_shutdown_type;
  _countdown_thermal_shutdown_type countdown_thermal_shutdown;

   typedef uint16_t _countdown_shot_limiting_type;
  _countdown_shot_limiting_type countdown_shot_limiting;

   typedef uint8_t _thermal_shutdown_type;
  _thermal_shutdown_type thermal_shutdown;

   typedef uint8_t _shot_limiting_type;
  _shot_limiting_type shot_limiting;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(THERMAL_SHUTDOWN_NORMAL)
  #undef THERMAL_SHUTDOWN_NORMAL
#endif
#if defined(_WIN32) && defined(THERMAL_SHUTDOWN_IMMINENT)
  #undef THERMAL_SHUTDOWN_IMMINENT
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_NORMAL)
  #undef SHOT_LIMITING_NORMAL
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_IMMINENT)
  #undef SHOT_LIMITING_IMMINENT
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_0_10)
  #undef SHOT_LIMITING_REDUCTION_0_10
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_10_20)
  #undef SHOT_LIMITING_REDUCTION_10_20
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_20_30)
  #undef SHOT_LIMITING_REDUCTION_20_30
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_30_40)
  #undef SHOT_LIMITING_REDUCTION_30_40
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_40_50)
  #undef SHOT_LIMITING_REDUCTION_40_50
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_50_60)
  #undef SHOT_LIMITING_REDUCTION_50_60
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_60_70)
  #undef SHOT_LIMITING_REDUCTION_60_70
#endif
#if defined(_WIN32) && defined(SHOT_LIMITING_REDUCTION_70_75)
  #undef SHOT_LIMITING_REDUCTION_70_75
#endif

  enum {
    THERMAL_SHUTDOWN_NORMAL = 0u,
    THERMAL_SHUTDOWN_IMMINENT = 1u,
    SHOT_LIMITING_NORMAL = 0u,
    SHOT_LIMITING_IMMINENT = 1u,
    SHOT_LIMITING_REDUCTION_0_10 = 2u,
    SHOT_LIMITING_REDUCTION_10_20 = 3u,
    SHOT_LIMITING_REDUCTION_20_30 = 4u,
    SHOT_LIMITING_REDUCTION_30_40 = 5u,
    SHOT_LIMITING_REDUCTION_40_50 = 6u,
    SHOT_LIMITING_REDUCTION_50_60 = 7u,
    SHOT_LIMITING_REDUCTION_60_70 = 8u,
    SHOT_LIMITING_REDUCTION_70_75 = 9u,
  };


  typedef boost::shared_ptr< ::ouster_ros::Telemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ouster_ros::Telemetry_<ContainerAllocator> const> ConstPtr;

}; // struct Telemetry_

typedef ::ouster_ros::Telemetry_<std::allocator<void> > Telemetry;

typedef boost::shared_ptr< ::ouster_ros::Telemetry > TelemetryPtr;
typedef boost::shared_ptr< ::ouster_ros::Telemetry const> TelemetryConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ouster_ros::Telemetry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ouster_ros::Telemetry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ouster_ros::Telemetry_<ContainerAllocator1> & lhs, const ::ouster_ros::Telemetry_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.countdown_thermal_shutdown == rhs.countdown_thermal_shutdown &&
    lhs.countdown_shot_limiting == rhs.countdown_shot_limiting &&
    lhs.thermal_shutdown == rhs.thermal_shutdown &&
    lhs.shot_limiting == rhs.shot_limiting;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ouster_ros::Telemetry_<ContainerAllocator1> & lhs, const ::ouster_ros::Telemetry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ouster_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ouster_ros::Telemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ouster_ros::Telemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ouster_ros::Telemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ouster_ros::Telemetry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ouster_ros::Telemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ouster_ros::Telemetry_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ouster_ros::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41824d1195ebb9ac184e7c24e9f33bfa";
  }

  static const char* value(const ::ouster_ros::Telemetry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41824d1195ebb9acULL;
  static const uint64_t static_value2 = 0x184e7c24e9f33bfaULL;
};

template<class ContainerAllocator>
struct DataType< ::ouster_ros::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ouster_ros/Telemetry";
  }

  static const char* value(const ::ouster_ros::Telemetry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ouster_ros::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message defines the telemetry data for Ouster sensors.\n"
"\n"
"# ThermalShutdownStatus thermal_shutdown\n"
"uint8 THERMAL_SHUTDOWN_NORMAL=0    # Normal operation\n"
"uint8 THERMAL_SHUTDOWN_IMMINENT=1  # Thermal Shutdown imminent\n"
"\n"
"# ShotLimitingStatus shot_limiting\n"
"uint8 SHOT_LIMITING_NORMAL=0          # Normal operation\n"
"uint8 SHOT_LIMITING_IMMINENT=1        # Shot limiting imminent\n"
"uint8 SHOT_LIMITING_REDUCTION_0_10=2  # Shot limiting reduction by 0 to 10%\n"
"uint8 SHOT_LIMITING_REDUCTION_10_20=3 # Shot limiting reduction by 10 to 20%\n"
"uint8 SHOT_LIMITING_REDUCTION_20_30=4 # Shot limiting reduction by 20 to 30%\n"
"uint8 SHOT_LIMITING_REDUCTION_30_40=5 # Shot limiting reduction by 30 to 40%\n"
"uint8 SHOT_LIMITING_REDUCTION_40_50=6 # Shot limiting reduction by 40 to 50%\n"
"uint8 SHOT_LIMITING_REDUCTION_50_60=7 # Shot limiting reduction by 50 to 60%\n"
"uint8 SHOT_LIMITING_REDUCTION_60_70=8 # Shot limiting reduction by 60 to 70%\n"
"uint8 SHOT_LIMITING_REDUCTION_70_75=9 # Shot limiting reduction by 70 to 80%\n"
"\n"
"# Message header\n"
"std_msgs/Header header\n"
"# Telemetry fields for more information on these fields and their meaning, please review:\n"
"# https://static.ouster.dev/sensor-docs/image_route1/image_route2/thermal_int_guide/therm_int_guide.html\n"
"uint16 countdown_thermal_shutdown # the thermal shutdown countdown.\n"
"uint16 countdown_shot_limiting    # the shot limiting countdown.\n"
"uint8 thermal_shutdown            # the thermal shutdown status. 0 = NORMAL, 1 = SHUTDOWN IMMINENT.\n"
"uint8 shot_limiting               # the shot limiting status. 0 = NORMAL OPERATION.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ouster_ros::Telemetry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ouster_ros::Telemetry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.countdown_thermal_shutdown);
      stream.next(m.countdown_shot_limiting);
      stream.next(m.thermal_shutdown);
      stream.next(m.shot_limiting);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Telemetry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ouster_ros::Telemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ouster_ros::Telemetry_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "countdown_thermal_shutdown: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.countdown_thermal_shutdown);
    s << indent << "countdown_shot_limiting: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.countdown_shot_limiting);
    s << indent << "thermal_shutdown: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.thermal_shutdown);
    s << indent << "shot_limiting: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shot_limiting);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_TELEMETRY_H
