version: "3.8"
services:
  ros:
    image: hcolesxyz/ros:noetic-l4t-r36.3.0
    container_name: ros
    privileged: true
    runtime: nvidia
    environment:
      #- DISPLAY
      - QT_X11_NO_MITSHM=1
    network_mode: "host"
    init: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/mapping/workspaces/mapping_robot/:/ros_noetic/mapping_ws/
      - /home/mapping/rosbag:/data
      - /mnt/ssd:/data2
      - /dev/:/dev/
        #entrypoint: [""]
    tty: true
    stdin_open: true
    restart: unless-stopped
    working_dir: /ros_noetic/mapping_ws/
