// Generated by gencpp from file microstrain_inertial_msgs/Mip3dmGpioStateWriteRequest.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMGPIOSTATEWRITEREQUEST_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMGPIOSTATEWRITEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct Mip3dmGpioStateWriteRequest_
{
  typedef Mip3dmGpioStateWriteRequest_<ContainerAllocator> Type;

  Mip3dmGpioStateWriteRequest_()
    : pin(0)
    , state(false)  {
    }
  Mip3dmGpioStateWriteRequest_(const ContainerAllocator& _alloc)
    : pin(0)
    , state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _pin_type;
  _pin_type pin;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Mip3dmGpioStateWriteRequest_

typedef ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<std::allocator<void> > Mip3dmGpioStateWriteRequest;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest > Mip3dmGpioStateWriteRequestPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest const> Mip3dmGpioStateWriteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pin == rhs.pin &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83707be3fa18d2ffe57381ea034aa262";
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83707be3fa18d2ffULL;
  static const uint64_t static_value2 = 0xe57381ea034aa262ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/Mip3dmGpioStateWriteRequest";
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service definition for the MIP command https://files.microstrain.com/GQ7+User+Manual/external_content/dcp/Commands/0x0c/data/0x42.htm\n"
"\n"
"# GPIO pin number counting from 1. Cannot be 0.\n"
"uint8 pin\n"
"\n"
"# The pin state\n"
"bool state\n"
"\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mip3dmGpioStateWriteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::Mip3dmGpioStateWriteRequest_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pin);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMGPIOSTATEWRITEREQUEST_H
