// Generated by gencpp from file microstrain_inertial_msgs/Mip3dmCaptureGyroBiasResponse.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMCAPTUREGYROBIASRESPONSE_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMCAPTUREGYROBIASRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct Mip3dmCaptureGyroBiasResponse_
{
  typedef Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> Type;

  Mip3dmCaptureGyroBiasResponse_()
    : bias()  {
      bias.assign(0.0);
  }
  Mip3dmCaptureGyroBiasResponse_(const ContainerAllocator& _alloc)
    : bias()  {
  (void)_alloc;
      bias.assign(0.0);
  }



   typedef boost::array<float, 3>  _bias_type;
  _bias_type bias;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Mip3dmCaptureGyroBiasResponse_

typedef ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<std::allocator<void> > Mip3dmCaptureGyroBiasResponse;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse > Mip3dmCaptureGyroBiasResponsePtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse const> Mip3dmCaptureGyroBiasResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator2> & rhs)
{
  return lhs.bias == rhs.bias;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3544fdea5e4e5d21daeac4669eef238";
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3544fdea5e4e5d2ULL;
  static const uint64_t static_value2 = 0x1daeac4669eef238ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/Mip3dmCaptureGyroBiasResponse";
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] bias\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bias);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mip3dmCaptureGyroBiasResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse_<ContainerAllocator>& v)
  {
    s << indent << "bias[]" << std::endl;
    for (size_t i = 0; i < v.bias.size(); ++i)
    {
      s << indent << "  bias[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.bias[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMCAPTUREGYROBIASRESPONSE_H
