// Generated by gencpp from file microstrain_inertial_msgs/Mip3dmCaptureGyroBias.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMCAPTUREGYROBIAS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMCAPTUREGYROBIAS_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/Mip3dmCaptureGyroBiasRequest.h>
#include <microstrain_inertial_msgs/Mip3dmCaptureGyroBiasResponse.h>


namespace microstrain_inertial_msgs
{

struct Mip3dmCaptureGyroBias
{

typedef Mip3dmCaptureGyroBiasRequest Request;
typedef Mip3dmCaptureGyroBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Mip3dmCaptureGyroBias
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias > {
  static const char* value()
  {
    return "c3544fdea5e4e5d21daeac4669eef238";
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/Mip3dmCaptureGyroBias";
  }

  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >
template<>
struct DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >
template<>
struct DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::Mip3dmCaptureGyroBias >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::Mip3dmCaptureGyroBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIP3DMCAPTUREGYROBIAS_H
