// Generated by gencpp from file microstrain_inertial_msgs/MipBaseGetDeviceInformation.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPBASEGETDEVICEINFORMATION_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPBASEGETDEVICEINFORMATION_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/MipBaseGetDeviceInformationRequest.h>
#include <microstrain_inertial_msgs/MipBaseGetDeviceInformationResponse.h>


namespace microstrain_inertial_msgs
{

struct MipBaseGetDeviceInformation
{

typedef MipBaseGetDeviceInformationRequest Request;
typedef MipBaseGetDeviceInformationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MipBaseGetDeviceInformation
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation > {
  static const char* value()
  {
    return "2c655b109370cba7cdc7620bb1869aa5";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipBaseGetDeviceInformation&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipBaseGetDeviceInformation";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipBaseGetDeviceInformation&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::MipBaseGetDeviceInformationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >
template<>
struct DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::MipBaseGetDeviceInformationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::MipBaseGetDeviceInformationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >
template<>
struct DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformationResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::MipBaseGetDeviceInformation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::MipBaseGetDeviceInformationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPBASEGETDEVICEINFORMATION_H
