// Generated by gencpp from file microstrain_inertial_msgs/MipFilterAidingMeasurementSummary.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERAIDINGMEASUREMENTSUMMARY_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERAIDINGMEASUREMENTSUMMARY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <microstrain_inertial_msgs/MipHeader.h>
#include <microstrain_inertial_msgs/MipFilterAidingMeasurementSummaryIndicator.h>

namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipFilterAidingMeasurementSummary_
{
  typedef MipFilterAidingMeasurementSummary_<ContainerAllocator> Type;

  MipFilterAidingMeasurementSummary_()
    : header()
    , time_of_week(0.0)
    , source(0)
    , type(0)
    , indicator()  {
    }
  MipFilterAidingMeasurementSummary_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_of_week(0.0)
    , source(0)
    , type(0)
    , indicator(_alloc)  {
  (void)_alloc;
    }



   typedef  ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _time_of_week_type;
  _time_of_week_type time_of_week;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint8_t _type_type;
  _type_type type;

   typedef  ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummaryIndicator_<ContainerAllocator>  _indicator_type;
  _indicator_type indicator;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TYPE_GNSS)
  #undef TYPE_GNSS
#endif
#if defined(_WIN32) && defined(TYPE_DUAL_ANTENNA)
  #undef TYPE_DUAL_ANTENNA
#endif
#if defined(_WIN32) && defined(TYPE_HEADING)
  #undef TYPE_HEADING
#endif
#if defined(_WIN32) && defined(TYPE_PRESSURE)
  #undef TYPE_PRESSURE
#endif
#if defined(_WIN32) && defined(TYPE_MAGNETOMETER)
  #undef TYPE_MAGNETOMETER
#endif
#if defined(_WIN32) && defined(TYPE_SPEED)
  #undef TYPE_SPEED
#endif

  enum {
    TYPE_GNSS = 1u,
    TYPE_DUAL_ANTENNA = 2u,
    TYPE_HEADING = 3u,
    TYPE_PRESSURE = 4u,
    TYPE_MAGNETOMETER = 5u,
    TYPE_SPEED = 6u,
  };


  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> const> ConstPtr;

}; // struct MipFilterAidingMeasurementSummary_

typedef ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<std::allocator<void> > MipFilterAidingMeasurementSummary;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary > MipFilterAidingMeasurementSummaryPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary const> MipFilterAidingMeasurementSummaryConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time_of_week == rhs.time_of_week &&
    lhs.source == rhs.source &&
    lhs.type == rhs.type &&
    lhs.indicator == rhs.indicator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a98270a16f24fc609dbe34498053146";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a98270a16f24fc6ULL;
  static const uint64_t static_value2 = 0x09dbe34498053146ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipFilterAidingMeasurementSummary";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the MIP field https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_aiding_measurement_summary.htm\n"
"\n"
"# Header containing common information\n"
"#   header.frame_id has no meaning in this message\n"
"microstrain_inertial_msgs/MipHeader header\n"
"\n"
"# GPS time of week (seconds)\n"
"float64 time_of_week\n"
"\n"
"# Source used when type is set to TYPE_GNSS to specify which GNSS module this message is for\n"
"uint8 source\n"
"\n"
"# Type of the aiding measurement. See TYPE_* enums for possible values\n"
"uint8 type\n"
"\n"
"# Parsed version of indicator bitfield\n"
"microstrain_inertial_msgs/MipFilterAidingMeasurementSummaryIndicator indicator\n"
"\n"
"# Possible values for type\n"
"uint8 TYPE_GNSS         = 1\n"
"uint8 TYPE_DUAL_ANTENNA = 2\n"
"uint8 TYPE_HEADING      = 3\n"
"uint8 TYPE_PRESSURE     = 4\n"
"uint8 TYPE_MAGNETOMETER = 5\n"
"uint8 TYPE_SPEED        = 6\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipHeader\n"
"# Represents a standard header that all MIP fields should include at the beginning of their message definition\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# Standard ROS header.\n"
"#   header.stamp will always be populated with the ROS time that this message was populated\n"
"#   header.frame_id is dependent on the full message definition. Most messages will not use this\n"
"std_msgs/Header header\n"
"\n"
"# If the message was triggered by an event, this will be set, otherwise it will be set to 0 (will be 0 most of the time)\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_event_source.htm\n"
"uint8 event_source\n"
"\n"
"# Reference timestamp of when the data was sampled if the device supports it. For devices that do not support this, it will always be 0\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_reference_timestamp.htm\n"
"uint64 reference_timestamp\n"
"\n"
"# GPS timestamp of when the data was sampled if the device supports it\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"# Note that this timestamp may be blank in certain messages, but there will often be equivalent fields in the messages\n"
"microstrain_inertial_msgs/MipGpsTimestamp gps_timestamp\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestamp\n"
"# Definition of a GPS timestamp.\n"
"# For more information see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# GPS time of week (seconds)\n"
"float64 tow\n"
"\n"
"# GPS Week number since 1980 (weeks)\n"
"uint16 week_number\n"
"\n"
"# Valid Flags bitfield\n"
"microstrain_inertial_msgs/MipGpsTimestampValidFlags valid_flags\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestampValidFlags\n"
"# Message definition for the valid_flags field of https://files.microstrain.com/CV7+Online/external_content/dcp/Data/0xff/data/0xd3.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"# Whole number seconds TOW has been set\n"
"bool tow\n"
"\n"
"# Week number has been set\n"
"bool week_number\n"
"\n"
"# Both TOW and Week Number have been set\n"
"bool time_valid\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipFilterAidingMeasurementSummaryIndicator\n"
"# Message definition for the indicator field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_aiding_measurement_summary.htm?Highlight=filter%20aiding%20measurement\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"bool enabled\n"
"bool used\n"
"bool residual_high_warning\n"
"bool sample_time_warning\n"
"bool configuration_error\n"
"bool max_num_meas_exceeded\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_of_week);
      stream.next(m.source);
      stream.next(m.type);
      stream.next(m.indicator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipFilterAidingMeasurementSummary_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummary_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_of_week: ";
    Printer<double>::stream(s, indent + "  ", v.time_of_week);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "indicator: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipFilterAidingMeasurementSummaryIndicator_<ContainerAllocator> >::stream(s, indent + "  ", v.indicator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERAIDINGMEASUREMENTSUMMARY_H
