// Generated by gencpp from file microstrain_inertial_msgs/MipFilterStatusGq7StatusFlags.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUSGQ7STATUSFLAGS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUSGQ7STATUSFLAGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipFilterStatusGq7StatusFlags_
{
  typedef MipFilterStatusGq7StatusFlags_<ContainerAllocator> Type;

  MipFilterStatusGq7StatusFlags_()
    : filter_condition(0)
    , roll_pitch_warning(false)
    , heading_warning(false)
    , position_warning(false)
    , velocity_warning(false)
    , imu_bias_warning(false)
    , gnss_clk_warning(false)
    , antenna_lever_arm_warning(false)
    , mounting_transform_warning(false)
    , time_sync_warning(false)
    , solution_error(false)  {
    }
  MipFilterStatusGq7StatusFlags_(const ContainerAllocator& _alloc)
    : filter_condition(0)
    , roll_pitch_warning(false)
    , heading_warning(false)
    , position_warning(false)
    , velocity_warning(false)
    , imu_bias_warning(false)
    , gnss_clk_warning(false)
    , antenna_lever_arm_warning(false)
    , mounting_transform_warning(false)
    , time_sync_warning(false)
    , solution_error(false)  {
  (void)_alloc;
    }



   typedef uint8_t _filter_condition_type;
  _filter_condition_type filter_condition;

   typedef uint8_t _roll_pitch_warning_type;
  _roll_pitch_warning_type roll_pitch_warning;

   typedef uint8_t _heading_warning_type;
  _heading_warning_type heading_warning;

   typedef uint8_t _position_warning_type;
  _position_warning_type position_warning;

   typedef uint8_t _velocity_warning_type;
  _velocity_warning_type velocity_warning;

   typedef uint8_t _imu_bias_warning_type;
  _imu_bias_warning_type imu_bias_warning;

   typedef uint8_t _gnss_clk_warning_type;
  _gnss_clk_warning_type gnss_clk_warning;

   typedef uint8_t _antenna_lever_arm_warning_type;
  _antenna_lever_arm_warning_type antenna_lever_arm_warning;

   typedef uint8_t _mounting_transform_warning_type;
  _mounting_transform_warning_type mounting_transform_warning;

   typedef uint8_t _time_sync_warning_type;
  _time_sync_warning_type time_sync_warning;

   typedef uint8_t _solution_error_type;
  _solution_error_type solution_error;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FILTER_CONDITION_STABLE)
  #undef FILTER_CONDITION_STABLE
#endif
#if defined(_WIN32) && defined(FILTER_CONDITION_CONVERGING)
  #undef FILTER_CONDITION_CONVERGING
#endif
#if defined(_WIN32) && defined(FILTER_CONDITION_UNSTABLE)
  #undef FILTER_CONDITION_UNSTABLE
#endif

  enum {
    FILTER_CONDITION_STABLE = 1u,
    FILTER_CONDITION_CONVERGING = 2u,
    FILTER_CONDITION_UNSTABLE = 3u,
  };


  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> const> ConstPtr;

}; // struct MipFilterStatusGq7StatusFlags_

typedef ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<std::allocator<void> > MipFilterStatusGq7StatusFlags;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags > MipFilterStatusGq7StatusFlagsPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags const> MipFilterStatusGq7StatusFlagsConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator2> & rhs)
{
  return lhs.filter_condition == rhs.filter_condition &&
    lhs.roll_pitch_warning == rhs.roll_pitch_warning &&
    lhs.heading_warning == rhs.heading_warning &&
    lhs.position_warning == rhs.position_warning &&
    lhs.velocity_warning == rhs.velocity_warning &&
    lhs.imu_bias_warning == rhs.imu_bias_warning &&
    lhs.gnss_clk_warning == rhs.gnss_clk_warning &&
    lhs.antenna_lever_arm_warning == rhs.antenna_lever_arm_warning &&
    lhs.mounting_transform_warning == rhs.mounting_transform_warning &&
    lhs.time_sync_warning == rhs.time_sync_warning &&
    lhs.solution_error == rhs.solution_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1db9853b9f08ade89304b0b0fc0f9df7";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1db9853b9f08ade8ULL;
  static const uint64_t static_value2 = 0x9304b0b0fc0f9df7ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipFilterStatusGq7StatusFlags";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the Status Flags (GQ7, CV7, etc.) field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_status.htm?Highlight=filter%20status\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"uint8 filter_condition  # See FILTER_CONDITION_* enums for possible values\n"
"bool  roll_pitch_warning\n"
"bool  heading_warning\n"
"bool  position_warning\n"
"bool  velocity_warning\n"
"bool  imu_bias_warning\n"
"bool  gnss_clk_warning\n"
"bool  antenna_lever_arm_warning\n"
"bool  mounting_transform_warning\n"
"bool  time_sync_warning  # No time synchronization pulse detected\n"
"bool  solution_error  # This includes all bits between 12 and 15, if any of them are set there is a GQ7 solution error\n"
"\n"
"# Possible values for filter_condition when the connected device is a prospect device (GQ7, CV7, etc)\n"
"uint8 FILTER_CONDITION_STABLE     = 1\n"
"uint8 FILTER_CONDITION_CONVERGING = 2\n"
"uint8 FILTER_CONDITION_UNSTABLE   = 3\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filter_condition);
      stream.next(m.roll_pitch_warning);
      stream.next(m.heading_warning);
      stream.next(m.position_warning);
      stream.next(m.velocity_warning);
      stream.next(m.imu_bias_warning);
      stream.next(m.gnss_clk_warning);
      stream.next(m.antenna_lever_arm_warning);
      stream.next(m.mounting_transform_warning);
      stream.next(m.time_sync_warning);
      stream.next(m.solution_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipFilterStatusGq7StatusFlags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator>& v)
  {
    s << indent << "filter_condition: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.filter_condition);
    s << indent << "roll_pitch_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.roll_pitch_warning);
    s << indent << "heading_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.heading_warning);
    s << indent << "position_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_warning);
    s << indent << "velocity_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.velocity_warning);
    s << indent << "imu_bias_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.imu_bias_warning);
    s << indent << "gnss_clk_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gnss_clk_warning);
    s << indent << "antenna_lever_arm_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.antenna_lever_arm_warning);
    s << indent << "mounting_transform_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mounting_transform_warning);
    s << indent << "time_sync_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.time_sync_warning);
    s << indent << "solution_error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solution_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUSGQ7STATUSFLAGS_H
