// Generated by gencpp from file microstrain_inertial_msgs/MipFilterStatus.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <microstrain_inertial_msgs/MipHeader.h>
#include <microstrain_inertial_msgs/MipFilterStatusGx5StatusFlags.h>
#include <microstrain_inertial_msgs/MipFilterStatusGq7StatusFlags.h>

namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipFilterStatus_
{
  typedef MipFilterStatus_<ContainerAllocator> Type;

  MipFilterStatus_()
    : header()
    , filter_state(0)
    , dynamics_mode(0)
    , gx5_status_flags()
    , gq7_status_flags()  {
    }
  MipFilterStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , filter_state(0)
    , dynamics_mode(0)
    , gx5_status_flags(_alloc)
    , gq7_status_flags(_alloc)  {
  (void)_alloc;
    }



   typedef  ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _filter_state_type;
  _filter_state_type filter_state;

   typedef uint16_t _dynamics_mode_type;
  _dynamics_mode_type dynamics_mode;

   typedef  ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator>  _gx5_status_flags_type;
  _gx5_status_flags_type gx5_status_flags;

   typedef  ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator>  _gq7_status_flags_type;
  _gq7_status_flags_type gq7_status_flags;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FILTER_STATE_GX5_STARTUP)
  #undef FILTER_STATE_GX5_STARTUP
#endif
#if defined(_WIN32) && defined(FILTER_STATE_GX5_INIT)
  #undef FILTER_STATE_GX5_INIT
#endif
#if defined(_WIN32) && defined(FILTER_STATE_GX5_RUN_SOLUTION_VALID)
  #undef FILTER_STATE_GX5_RUN_SOLUTION_VALID
#endif
#if defined(_WIN32) && defined(FILTER_STATE_GX5_RUN_SOLUTION_ERROR)
  #undef FILTER_STATE_GX5_RUN_SOLUTION_ERROR
#endif
#if defined(_WIN32) && defined(FILTER_STATE_GQ7_INIT)
  #undef FILTER_STATE_GQ7_INIT
#endif
#if defined(_WIN32) && defined(FILTER_STATE_GQ7_VERT_GYRO)
  #undef FILTER_STATE_GQ7_VERT_GYRO
#endif
#if defined(_WIN32) && defined(FILTER_STATE_GQ7_AHRS)
  #undef FILTER_STATE_GQ7_AHRS
#endif
#if defined(_WIN32) && defined(FILTER_STATE_GQ7_FULL_NAV)
  #undef FILTER_STATE_GQ7_FULL_NAV
#endif
#if defined(_WIN32) && defined(DYNAMICS_MODE_GX5_PORTABLE)
  #undef DYNAMICS_MODE_GX5_PORTABLE
#endif
#if defined(_WIN32) && defined(DYNAMICS_MODE_GX5_AUTOMOTIVE)
  #undef DYNAMICS_MODE_GX5_AUTOMOTIVE
#endif
#if defined(_WIN32) && defined(DYNAMICS_MODE_GX5_AIRBORNE)
  #undef DYNAMICS_MODE_GX5_AIRBORNE
#endif
#if defined(_WIN32) && defined(DYNAMICS_MODE_GQ7_DEFAULT)
  #undef DYNAMICS_MODE_GQ7_DEFAULT
#endif

  enum {
    FILTER_STATE_GX5_STARTUP = 0u,
    FILTER_STATE_GX5_INIT = 1u,
    FILTER_STATE_GX5_RUN_SOLUTION_VALID = 2u,
    FILTER_STATE_GX5_RUN_SOLUTION_ERROR = 3u,
    FILTER_STATE_GQ7_INIT = 1u,
    FILTER_STATE_GQ7_VERT_GYRO = 2u,
    FILTER_STATE_GQ7_AHRS = 3u,
    FILTER_STATE_GQ7_FULL_NAV = 4u,
    DYNAMICS_MODE_GX5_PORTABLE = 1u,
    DYNAMICS_MODE_GX5_AUTOMOTIVE = 2u,
    DYNAMICS_MODE_GX5_AIRBORNE = 3u,
    DYNAMICS_MODE_GQ7_DEFAULT = 1u,
  };


  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MipFilterStatus_

typedef ::microstrain_inertial_msgs::MipFilterStatus_<std::allocator<void> > MipFilterStatus;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatus > MipFilterStatusPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatus const> MipFilterStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.filter_state == rhs.filter_state &&
    lhs.dynamics_mode == rhs.dynamics_mode &&
    lhs.gx5_status_flags == rhs.gx5_status_flags &&
    lhs.gq7_status_flags == rhs.gq7_status_flags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4aa95a55ec5be9507ec04d6ed003846c";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4aa95a55ec5be950ULL;
  static const uint64_t static_value2 = 0x7ec04d6ed003846cULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipFilterStatus";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the MIP field https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_status.htm\n"
"\n"
"# Header containing common information\n"
"#   header.frame_id has no meaning in this message\n"
"microstrain_inertial_msgs/MipHeader header\n"
"\n"
"# Device-specific filter state. Please consult the user manual for definition. See FILTER_STATE_* enums for possible values\n"
"uint16 filter_state\n"
"\n"
"# Device-specific dynamics mode. Please consult the user manual for definition. See DYNAMICS_MODE_* enums for possible values\n"
"# Note that for prospect devices (GQ7, CV7, etc), this field has a default value, and should be mostly ignored\n"
"uint16 dynamics_mode\n"
"\n"
"# Parsed out version of the Status Flags bitfield when the connected device is a philo device (GX5, CX5, CV5, etc)\n"
"microstrain_inertial_msgs/MipFilterStatusGx5StatusFlags gx5_status_flags\n"
"\n"
"# Parsed out version of the Status Flags bitfield when the connected device is a prospect device (GQ7, CV7, etc)\n"
"microstrain_inertial_msgs/MipFilterStatusGq7StatusFlags gq7_status_flags\n"
"\n"
"# Possible values for filter_state when the connected device is a philo device (GX5, CX5, CV5, etc)\n"
"uint16 FILTER_STATE_GX5_STARTUP            = 0\n"
"uint16 FILTER_STATE_GX5_INIT               = 1\n"
"uint16 FILTER_STATE_GX5_RUN_SOLUTION_VALID = 2\n"
"uint16 FILTER_STATE_GX5_RUN_SOLUTION_ERROR = 3\n"
"\n"
"# Possible values for filter_state when the connected device is a prospect device (GQ7, CV7, etc)\n"
"uint16 FILTER_STATE_GQ7_INIT      = 1\n"
"uint16 FILTER_STATE_GQ7_VERT_GYRO = 2\n"
"uint16 FILTER_STATE_GQ7_AHRS      = 3\n"
"uint16 FILTER_STATE_GQ7_FULL_NAV  = 4\n"
"\n"
"# Possible values for dynamics_mode when the connected device is a philo device (GX5, CX5, CV5, etc)\n"
"uint16 DYNAMICS_MODE_GX5_PORTABLE   = 1\n"
"uint16 DYNAMICS_MODE_GX5_AUTOMOTIVE = 2\n"
"uint16 DYNAMICS_MODE_GX5_AIRBORNE   = 3\n"
"\n"
"# Possible values for dynamics_mode when the connected device is a prospect device (GQ7, CV7, etc)\n"
"# Note that on older firmware the GQ7 will often report 0 for it's dynamics mode, it is strongly advised to ignore this field\n"
"uint16 DYNAMICS_MODE_GQ7_DEFAULT = 1\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipHeader\n"
"# Represents a standard header that all MIP fields should include at the beginning of their message definition\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# Standard ROS header.\n"
"#   header.stamp will always be populated with the ROS time that this message was populated\n"
"#   header.frame_id is dependent on the full message definition. Most messages will not use this\n"
"std_msgs/Header header\n"
"\n"
"# If the message was triggered by an event, this will be set, otherwise it will be set to 0 (will be 0 most of the time)\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_event_source.htm\n"
"uint8 event_source\n"
"\n"
"# Reference timestamp of when the data was sampled if the device supports it. For devices that do not support this, it will always be 0\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_reference_timestamp.htm\n"
"uint64 reference_timestamp\n"
"\n"
"# GPS timestamp of when the data was sampled if the device supports it\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"# Note that this timestamp may be blank in certain messages, but there will often be equivalent fields in the messages\n"
"microstrain_inertial_msgs/MipGpsTimestamp gps_timestamp\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestamp\n"
"# Definition of a GPS timestamp.\n"
"# For more information see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# GPS time of week (seconds)\n"
"float64 tow\n"
"\n"
"# GPS Week number since 1980 (weeks)\n"
"uint16 week_number\n"
"\n"
"# Valid Flags bitfield\n"
"microstrain_inertial_msgs/MipGpsTimestampValidFlags valid_flags\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestampValidFlags\n"
"# Message definition for the valid_flags field of https://files.microstrain.com/CV7+Online/external_content/dcp/Data/0xff/data/0xd3.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"# Whole number seconds TOW has been set\n"
"bool tow\n"
"\n"
"# Week number has been set\n"
"bool week_number\n"
"\n"
"# Both TOW and Week Number have been set\n"
"bool time_valid\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipFilterStatusGx5StatusFlags\n"
"# Message definition for the Status Flags (GX5, CV5, CX5, etc.) field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_status.htm?Highlight=filter%20status\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"bool init_no_attitude\n"
"bool init_no_position_velocity\n"
"bool run_imu_unavailable\n"
"bool run_gps_unavailable\n"
"bool run_matrix_singularity\n"
"bool run_position_covariance_warning\n"
"bool run_velocity_covariance_warning\n"
"bool run_attitude_covariance_warning\n"
"bool run_nan_in_solution_warning\n"
"bool run_gyro_bias_est_high_warning\n"
"bool run_accel_bias_est_high_warning\n"
"bool run_gyro_scale_factor_est_high_warning\n"
"bool run_accel_scale_factor_est_high_warning\n"
"bool run_mag_bias_est_high_warning\n"
"bool run_ant_offset_correction_est_high_warning\n"
"bool run_mag_hard_iron_est_high_warning\n"
"bool run_mag_soft_iron_est_high_warning\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipFilterStatusGq7StatusFlags\n"
"# Message definition for the Status Flags (GQ7, CV7, etc.) field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_status.htm?Highlight=filter%20status\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"uint8 filter_condition  # See FILTER_CONDITION_* enums for possible values\n"
"bool  roll_pitch_warning\n"
"bool  heading_warning\n"
"bool  position_warning\n"
"bool  velocity_warning\n"
"bool  imu_bias_warning\n"
"bool  gnss_clk_warning\n"
"bool  antenna_lever_arm_warning\n"
"bool  mounting_transform_warning\n"
"bool  time_sync_warning  # No time synchronization pulse detected\n"
"bool  solution_error  # This includes all bits between 12 and 15, if any of them are set there is a GQ7 solution error\n"
"\n"
"# Possible values for filter_condition when the connected device is a prospect device (GQ7, CV7, etc)\n"
"uint8 FILTER_CONDITION_STABLE     = 1\n"
"uint8 FILTER_CONDITION_CONVERGING = 2\n"
"uint8 FILTER_CONDITION_UNSTABLE   = 3\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.filter_state);
      stream.next(m.dynamics_mode);
      stream.next(m.gx5_status_flags);
      stream.next(m.gq7_status_flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipFilterStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipFilterStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "filter_state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.filter_state);
    s << indent << "dynamics_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.dynamics_mode);
    s << indent << "gx5_status_flags: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >::stream(s, indent + "  ", v.gx5_status_flags);
    s << indent << "gq7_status_flags: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipFilterStatusGq7StatusFlags_<ContainerAllocator> >::stream(s, indent + "  ", v.gq7_status_flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUS_H
