// Generated by gencpp from file microstrain_inertial_msgs/MipFilterStatusGx5StatusFlags.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUSGX5STATUSFLAGS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUSGX5STATUSFLAGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipFilterStatusGx5StatusFlags_
{
  typedef MipFilterStatusGx5StatusFlags_<ContainerAllocator> Type;

  MipFilterStatusGx5StatusFlags_()
    : init_no_attitude(false)
    , init_no_position_velocity(false)
    , run_imu_unavailable(false)
    , run_gps_unavailable(false)
    , run_matrix_singularity(false)
    , run_position_covariance_warning(false)
    , run_velocity_covariance_warning(false)
    , run_attitude_covariance_warning(false)
    , run_nan_in_solution_warning(false)
    , run_gyro_bias_est_high_warning(false)
    , run_accel_bias_est_high_warning(false)
    , run_gyro_scale_factor_est_high_warning(false)
    , run_accel_scale_factor_est_high_warning(false)
    , run_mag_bias_est_high_warning(false)
    , run_ant_offset_correction_est_high_warning(false)
    , run_mag_hard_iron_est_high_warning(false)
    , run_mag_soft_iron_est_high_warning(false)  {
    }
  MipFilterStatusGx5StatusFlags_(const ContainerAllocator& _alloc)
    : init_no_attitude(false)
    , init_no_position_velocity(false)
    , run_imu_unavailable(false)
    , run_gps_unavailable(false)
    , run_matrix_singularity(false)
    , run_position_covariance_warning(false)
    , run_velocity_covariance_warning(false)
    , run_attitude_covariance_warning(false)
    , run_nan_in_solution_warning(false)
    , run_gyro_bias_est_high_warning(false)
    , run_accel_bias_est_high_warning(false)
    , run_gyro_scale_factor_est_high_warning(false)
    , run_accel_scale_factor_est_high_warning(false)
    , run_mag_bias_est_high_warning(false)
    , run_ant_offset_correction_est_high_warning(false)
    , run_mag_hard_iron_est_high_warning(false)
    , run_mag_soft_iron_est_high_warning(false)  {
  (void)_alloc;
    }



   typedef uint8_t _init_no_attitude_type;
  _init_no_attitude_type init_no_attitude;

   typedef uint8_t _init_no_position_velocity_type;
  _init_no_position_velocity_type init_no_position_velocity;

   typedef uint8_t _run_imu_unavailable_type;
  _run_imu_unavailable_type run_imu_unavailable;

   typedef uint8_t _run_gps_unavailable_type;
  _run_gps_unavailable_type run_gps_unavailable;

   typedef uint8_t _run_matrix_singularity_type;
  _run_matrix_singularity_type run_matrix_singularity;

   typedef uint8_t _run_position_covariance_warning_type;
  _run_position_covariance_warning_type run_position_covariance_warning;

   typedef uint8_t _run_velocity_covariance_warning_type;
  _run_velocity_covariance_warning_type run_velocity_covariance_warning;

   typedef uint8_t _run_attitude_covariance_warning_type;
  _run_attitude_covariance_warning_type run_attitude_covariance_warning;

   typedef uint8_t _run_nan_in_solution_warning_type;
  _run_nan_in_solution_warning_type run_nan_in_solution_warning;

   typedef uint8_t _run_gyro_bias_est_high_warning_type;
  _run_gyro_bias_est_high_warning_type run_gyro_bias_est_high_warning;

   typedef uint8_t _run_accel_bias_est_high_warning_type;
  _run_accel_bias_est_high_warning_type run_accel_bias_est_high_warning;

   typedef uint8_t _run_gyro_scale_factor_est_high_warning_type;
  _run_gyro_scale_factor_est_high_warning_type run_gyro_scale_factor_est_high_warning;

   typedef uint8_t _run_accel_scale_factor_est_high_warning_type;
  _run_accel_scale_factor_est_high_warning_type run_accel_scale_factor_est_high_warning;

   typedef uint8_t _run_mag_bias_est_high_warning_type;
  _run_mag_bias_est_high_warning_type run_mag_bias_est_high_warning;

   typedef uint8_t _run_ant_offset_correction_est_high_warning_type;
  _run_ant_offset_correction_est_high_warning_type run_ant_offset_correction_est_high_warning;

   typedef uint8_t _run_mag_hard_iron_est_high_warning_type;
  _run_mag_hard_iron_est_high_warning_type run_mag_hard_iron_est_high_warning;

   typedef uint8_t _run_mag_soft_iron_est_high_warning_type;
  _run_mag_soft_iron_est_high_warning_type run_mag_soft_iron_est_high_warning;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> const> ConstPtr;

}; // struct MipFilterStatusGx5StatusFlags_

typedef ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<std::allocator<void> > MipFilterStatusGx5StatusFlags;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags > MipFilterStatusGx5StatusFlagsPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags const> MipFilterStatusGx5StatusFlagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator2> & rhs)
{
  return lhs.init_no_attitude == rhs.init_no_attitude &&
    lhs.init_no_position_velocity == rhs.init_no_position_velocity &&
    lhs.run_imu_unavailable == rhs.run_imu_unavailable &&
    lhs.run_gps_unavailable == rhs.run_gps_unavailable &&
    lhs.run_matrix_singularity == rhs.run_matrix_singularity &&
    lhs.run_position_covariance_warning == rhs.run_position_covariance_warning &&
    lhs.run_velocity_covariance_warning == rhs.run_velocity_covariance_warning &&
    lhs.run_attitude_covariance_warning == rhs.run_attitude_covariance_warning &&
    lhs.run_nan_in_solution_warning == rhs.run_nan_in_solution_warning &&
    lhs.run_gyro_bias_est_high_warning == rhs.run_gyro_bias_est_high_warning &&
    lhs.run_accel_bias_est_high_warning == rhs.run_accel_bias_est_high_warning &&
    lhs.run_gyro_scale_factor_est_high_warning == rhs.run_gyro_scale_factor_est_high_warning &&
    lhs.run_accel_scale_factor_est_high_warning == rhs.run_accel_scale_factor_est_high_warning &&
    lhs.run_mag_bias_est_high_warning == rhs.run_mag_bias_est_high_warning &&
    lhs.run_ant_offset_correction_est_high_warning == rhs.run_ant_offset_correction_est_high_warning &&
    lhs.run_mag_hard_iron_est_high_warning == rhs.run_mag_hard_iron_est_high_warning &&
    lhs.run_mag_soft_iron_est_high_warning == rhs.run_mag_soft_iron_est_high_warning;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82e4f81fef282c1265a9db8f5c2b8418";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82e4f81fef282c12ULL;
  static const uint64_t static_value2 = 0x65a9db8f5c2b8418ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipFilterStatusGx5StatusFlags";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the Status Flags (GX5, CV5, CX5, etc.) field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_status.htm?Highlight=filter%20status\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"bool init_no_attitude\n"
"bool init_no_position_velocity\n"
"bool run_imu_unavailable\n"
"bool run_gps_unavailable\n"
"bool run_matrix_singularity\n"
"bool run_position_covariance_warning\n"
"bool run_velocity_covariance_warning\n"
"bool run_attitude_covariance_warning\n"
"bool run_nan_in_solution_warning\n"
"bool run_gyro_bias_est_high_warning\n"
"bool run_accel_bias_est_high_warning\n"
"bool run_gyro_scale_factor_est_high_warning\n"
"bool run_accel_scale_factor_est_high_warning\n"
"bool run_mag_bias_est_high_warning\n"
"bool run_ant_offset_correction_est_high_warning\n"
"bool run_mag_hard_iron_est_high_warning\n"
"bool run_mag_soft_iron_est_high_warning\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.init_no_attitude);
      stream.next(m.init_no_position_velocity);
      stream.next(m.run_imu_unavailable);
      stream.next(m.run_gps_unavailable);
      stream.next(m.run_matrix_singularity);
      stream.next(m.run_position_covariance_warning);
      stream.next(m.run_velocity_covariance_warning);
      stream.next(m.run_attitude_covariance_warning);
      stream.next(m.run_nan_in_solution_warning);
      stream.next(m.run_gyro_bias_est_high_warning);
      stream.next(m.run_accel_bias_est_high_warning);
      stream.next(m.run_gyro_scale_factor_est_high_warning);
      stream.next(m.run_accel_scale_factor_est_high_warning);
      stream.next(m.run_mag_bias_est_high_warning);
      stream.next(m.run_ant_offset_correction_est_high_warning);
      stream.next(m.run_mag_hard_iron_est_high_warning);
      stream.next(m.run_mag_soft_iron_est_high_warning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipFilterStatusGx5StatusFlags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipFilterStatusGx5StatusFlags_<ContainerAllocator>& v)
  {
    s << indent << "init_no_attitude: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.init_no_attitude);
    s << indent << "init_no_position_velocity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.init_no_position_velocity);
    s << indent << "run_imu_unavailable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_imu_unavailable);
    s << indent << "run_gps_unavailable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_gps_unavailable);
    s << indent << "run_matrix_singularity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_matrix_singularity);
    s << indent << "run_position_covariance_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_position_covariance_warning);
    s << indent << "run_velocity_covariance_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_velocity_covariance_warning);
    s << indent << "run_attitude_covariance_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_attitude_covariance_warning);
    s << indent << "run_nan_in_solution_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_nan_in_solution_warning);
    s << indent << "run_gyro_bias_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_gyro_bias_est_high_warning);
    s << indent << "run_accel_bias_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_accel_bias_est_high_warning);
    s << indent << "run_gyro_scale_factor_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_gyro_scale_factor_est_high_warning);
    s << indent << "run_accel_scale_factor_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_accel_scale_factor_est_high_warning);
    s << indent << "run_mag_bias_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_mag_bias_est_high_warning);
    s << indent << "run_ant_offset_correction_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_ant_offset_correction_est_high_warning);
    s << indent << "run_mag_hard_iron_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_mag_hard_iron_est_high_warning);
    s << indent << "run_mag_soft_iron_est_high_warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_mag_soft_iron_est_high_warning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPFILTERSTATUSGX5STATUSFLAGS_H
