// Generated by gencpp from file microstrain_inertial_msgs/MipGnssFixInfoFixFlags.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSFIXINFOFIXFLAGS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSFIXINFOFIXFLAGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipGnssFixInfoFixFlags_
{
  typedef MipGnssFixInfoFixFlags_<ContainerAllocator> Type;

  MipGnssFixInfoFixFlags_()
    : sbas_used(false)
    , dgnss_used(false)  {
    }
  MipGnssFixInfoFixFlags_(const ContainerAllocator& _alloc)
    : sbas_used(false)
    , dgnss_used(false)  {
  (void)_alloc;
    }



   typedef uint8_t _sbas_used_type;
  _sbas_used_type sbas_used;

   typedef uint8_t _dgnss_used_type;
  _dgnss_used_type dgnss_used;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> const> ConstPtr;

}; // struct MipGnssFixInfoFixFlags_

typedef ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<std::allocator<void> > MipGnssFixInfoFixFlags;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags > MipGnssFixInfoFixFlagsPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags const> MipGnssFixInfoFixFlagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator2> & rhs)
{
  return lhs.sbas_used == rhs.sbas_used &&
    lhs.dgnss_used == rhs.dgnss_used;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "200751727401aacbfb01ffdee0995730";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x200751727401aacbULL;
  static const uint64_t static_value2 = 0xfb01ffdee0995730ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipGnssFixInfoFixFlags";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the Fix Type field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/data/mip_field_gnss_fix_info.htm?Highlight=fix%20info\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"bool sbas_used\n"
"bool dgnss_used\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sbas_used);
      stream.next(m.dgnss_used);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipGnssFixInfoFixFlags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator>& v)
  {
    s << indent << "sbas_used: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sbas_used);
    s << indent << "dgnss_used: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dgnss_used);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSFIXINFOFIXFLAGS_H
