// Generated by gencpp from file microstrain_inertial_msgs/MipGnssFixInfo.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSFIXINFO_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSFIXINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <microstrain_inertial_msgs/MipHeader.h>
#include <microstrain_inertial_msgs/MipGnssFixInfoFixFlags.h>

namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipGnssFixInfo_
{
  typedef MipGnssFixInfo_<ContainerAllocator> Type;

  MipGnssFixInfo_()
    : header()
    , fix_type(0)
    , num_sv(0)
    , fix_flags()  {
    }
  MipGnssFixInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fix_type(0)
    , num_sv(0)
    , fix_flags(_alloc)  {
  (void)_alloc;
    }



   typedef  ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _fix_type_type;
  _fix_type_type fix_type;

   typedef uint8_t _num_sv_type;
  _num_sv_type num_sv;

   typedef  ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator>  _fix_flags_type;
  _fix_flags_type fix_flags;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FIX_TYPE_FIX_3D)
  #undef FIX_TYPE_FIX_3D
#endif
#if defined(_WIN32) && defined(FIX_TYPE_FIX_2D)
  #undef FIX_TYPE_FIX_2D
#endif
#if defined(_WIN32) && defined(FIX_TYPE_FIX_TIME_ONLY)
  #undef FIX_TYPE_FIX_TIME_ONLY
#endif
#if defined(_WIN32) && defined(FIX_TYPE_FIX_NONE)
  #undef FIX_TYPE_FIX_NONE
#endif
#if defined(_WIN32) && defined(FIX_TYPE_FIX_INVALID)
  #undef FIX_TYPE_FIX_INVALID
#endif
#if defined(_WIN32) && defined(FIX_TYPE_FIX_RTK_FLOAT)
  #undef FIX_TYPE_FIX_RTK_FLOAT
#endif
#if defined(_WIN32) && defined(FIX_TYPE_FIX_RTK_FIXED)
  #undef FIX_TYPE_FIX_RTK_FIXED
#endif

  enum {
    FIX_TYPE_FIX_3D = 0u,
    FIX_TYPE_FIX_2D = 1u,
    FIX_TYPE_FIX_TIME_ONLY = 2u,
    FIX_TYPE_FIX_NONE = 3u,
    FIX_TYPE_FIX_INVALID = 4u,
    FIX_TYPE_FIX_RTK_FLOAT = 5u,
    FIX_TYPE_FIX_RTK_FIXED = 6u,
  };


  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MipGnssFixInfo_

typedef ::microstrain_inertial_msgs::MipGnssFixInfo_<std::allocator<void> > MipGnssFixInfo;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfo > MipGnssFixInfoPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssFixInfo const> MipGnssFixInfoConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fix_type == rhs.fix_type &&
    lhs.num_sv == rhs.num_sv &&
    lhs.fix_flags == rhs.fix_flags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "981a71050cd7ff7c9ee9bd9a4ffe93a8";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x981a71050cd7ff7cULL;
  static const uint64_t static_value2 = 0x9ee9bd9a4ffe93a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipGnssFixInfo";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the MIP field https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/data/mip_field_gnss_fix_info.htm\n"
"\n"
"# Header containing common information\n"
"#   header.frame_id has no meaning in this message\n"
"microstrain_inertial_msgs/MipHeader header\n"
"\n"
"# Fix type. See FIX_TYPE_* enums for possible values\n"
"uint8 fix_type\n"
"\n"
"# Number of satellites in view for this receiver\n"
"uint8 num_sv\n"
"\n"
"# Parsed out version of the fix_flags bitfield\n"
"microstrain_inertial_msgs/MipGnssFixInfoFixFlags fix_flags\n"
"\n"
"# Valid values for the fix_type field\n"
"uint8 FIX_TYPE_FIX_3D        = 0\n"
"uint8 FIX_TYPE_FIX_2D        = 1\n"
"uint8 FIX_TYPE_FIX_TIME_ONLY = 2\n"
"uint8 FIX_TYPE_FIX_NONE      = 3\n"
"uint8 FIX_TYPE_FIX_INVALID   = 4\n"
"uint8 FIX_TYPE_FIX_RTK_FLOAT = 5\n"
"uint8 FIX_TYPE_FIX_RTK_FIXED = 6\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipHeader\n"
"# Represents a standard header that all MIP fields should include at the beginning of their message definition\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# Standard ROS header.\n"
"#   header.stamp will always be populated with the ROS time that this message was populated\n"
"#   header.frame_id is dependent on the full message definition. Most messages will not use this\n"
"std_msgs/Header header\n"
"\n"
"# If the message was triggered by an event, this will be set, otherwise it will be set to 0 (will be 0 most of the time)\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_event_source.htm\n"
"uint8 event_source\n"
"\n"
"# Reference timestamp of when the data was sampled if the device supports it. For devices that do not support this, it will always be 0\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_reference_timestamp.htm\n"
"uint64 reference_timestamp\n"
"\n"
"# GPS timestamp of when the data was sampled if the device supports it\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"# Note that this timestamp may be blank in certain messages, but there will often be equivalent fields in the messages\n"
"microstrain_inertial_msgs/MipGpsTimestamp gps_timestamp\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestamp\n"
"# Definition of a GPS timestamp.\n"
"# For more information see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# GPS time of week (seconds)\n"
"float64 tow\n"
"\n"
"# GPS Week number since 1980 (weeks)\n"
"uint16 week_number\n"
"\n"
"# Valid Flags bitfield\n"
"microstrain_inertial_msgs/MipGpsTimestampValidFlags valid_flags\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestampValidFlags\n"
"# Message definition for the valid_flags field of https://files.microstrain.com/CV7+Online/external_content/dcp/Data/0xff/data/0xd3.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"# Whole number seconds TOW has been set\n"
"bool tow\n"
"\n"
"# Week number has been set\n"
"bool week_number\n"
"\n"
"# Both TOW and Week Number have been set\n"
"bool time_valid\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGnssFixInfoFixFlags\n"
"# Message definition for the Fix Type field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/data/mip_field_gnss_fix_info.htm?Highlight=fix%20info\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"bool sbas_used\n"
"bool dgnss_used\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fix_type);
      stream.next(m.num_sv);
      stream.next(m.fix_flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipGnssFixInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipGnssFixInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fix_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fix_type);
    s << indent << "num_sv: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_sv);
    s << indent << "fix_flags: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipGnssFixInfoFixFlags_<ContainerAllocator> >::stream(s, indent + "  ", v.fix_flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSFIXINFO_H
