// Generated by gencpp from file microstrain_inertial_msgs/MipGnssSbasInfoSbasStatus.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSSBASINFOSBASSTATUS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSSBASINFOSBASSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipGnssSbasInfoSbasStatus_
{
  typedef MipGnssSbasInfoSbasStatus_<ContainerAllocator> Type;

  MipGnssSbasInfoSbasStatus_()
    : range_available(false)
    , corrections_available(false)
    , integrity_available(false)
    , test_mode(false)  {
    }
  MipGnssSbasInfoSbasStatus_(const ContainerAllocator& _alloc)
    : range_available(false)
    , corrections_available(false)
    , integrity_available(false)
    , test_mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _range_available_type;
  _range_available_type range_available;

   typedef uint8_t _corrections_available_type;
  _corrections_available_type corrections_available;

   typedef uint8_t _integrity_available_type;
  _integrity_available_type integrity_available;

   typedef uint8_t _test_mode_type;
  _test_mode_type test_mode;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MipGnssSbasInfoSbasStatus_

typedef ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<std::allocator<void> > MipGnssSbasInfoSbasStatus;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus > MipGnssSbasInfoSbasStatusPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus const> MipGnssSbasInfoSbasStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator2> & rhs)
{
  return lhs.range_available == rhs.range_available &&
    lhs.corrections_available == rhs.corrections_available &&
    lhs.integrity_available == rhs.integrity_available &&
    lhs.test_mode == rhs.test_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d44b1dcf4b6c5470a42c909b93caefc4";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd44b1dcf4b6c5470ULL;
  static const uint64_t static_value2 = 0xa42c909b93caefc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipGnssSbasInfoSbasStatus";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the Sbas Status field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/data/mip_field_gnss_sbas_info.htm?Highlight=sbas%20info\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"bool range_available\n"
"bool corrections_available\n"
"bool integrity_available\n"
"bool test_mode\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.range_available);
      stream.next(m.corrections_available);
      stream.next(m.integrity_available);
      stream.next(m.test_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipGnssSbasInfoSbasStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator>& v)
  {
    s << indent << "range_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.range_available);
    s << indent << "corrections_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.corrections_available);
    s << indent << "integrity_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.integrity_available);
    s << indent << "test_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.test_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSSBASINFOSBASSTATUS_H
