// Generated by gencpp from file microstrain_inertial_msgs/MipGnssSbasInfo.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSSBASINFO_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSSBASINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <microstrain_inertial_msgs/MipHeader.h>
#include <microstrain_inertial_msgs/MipGnssSbasInfoSbasStatus.h>

namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipGnssSbasInfo_
{
  typedef MipGnssSbasInfo_<ContainerAllocator> Type;

  MipGnssSbasInfo_()
    : header()
    , time_of_week(0.0)
    , week_number(0)
    , sbas_system(0)
    , sbas_id(0)
    , count(0)
    , sbas_status()  {
    }
  MipGnssSbasInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_of_week(0.0)
    , week_number(0)
    , sbas_system(0)
    , sbas_id(0)
    , count(0)
    , sbas_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _time_of_week_type;
  _time_of_week_type time_of_week;

   typedef uint16_t _week_number_type;
  _week_number_type week_number;

   typedef uint8_t _sbas_system_type;
  _sbas_system_type sbas_system;

   typedef uint8_t _sbas_id_type;
  _sbas_id_type sbas_id;

   typedef uint8_t _count_type;
  _count_type count;

   typedef  ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator>  _sbas_status_type;
  _sbas_status_type sbas_status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SBAS_SYSTEM_UNKNOWN)
  #undef SBAS_SYSTEM_UNKNOWN
#endif
#if defined(_WIN32) && defined(SBAS_SYSTEM_WAAS)
  #undef SBAS_SYSTEM_WAAS
#endif
#if defined(_WIN32) && defined(SBAS_SYSTEM_EGNOS)
  #undef SBAS_SYSTEM_EGNOS
#endif
#if defined(_WIN32) && defined(SBAS_SYSTEM_MSAS)
  #undef SBAS_SYSTEM_MSAS
#endif
#if defined(_WIN32) && defined(SBAS_SYSTEM_GAGAN)
  #undef SBAS_SYSTEM_GAGAN
#endif

  enum {
    SBAS_SYSTEM_UNKNOWN = 0u,
    SBAS_SYSTEM_WAAS = 1u,
    SBAS_SYSTEM_EGNOS = 2u,
    SBAS_SYSTEM_MSAS = 3u,
    SBAS_SYSTEM_GAGAN = 4u,
  };


  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MipGnssSbasInfo_

typedef ::microstrain_inertial_msgs::MipGnssSbasInfo_<std::allocator<void> > MipGnssSbasInfo;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfo > MipGnssSbasInfoPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssSbasInfo const> MipGnssSbasInfoConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time_of_week == rhs.time_of_week &&
    lhs.week_number == rhs.week_number &&
    lhs.sbas_system == rhs.sbas_system &&
    lhs.sbas_id == rhs.sbas_id &&
    lhs.count == rhs.count &&
    lhs.sbas_status == rhs.sbas_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bf8d39005d90e152e75be3cb6afe0a6";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bf8d39005d90e15ULL;
  static const uint64_t static_value2 = 0x2e75be3cb6afe0a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipGnssSbasInfo";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the MIP field https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/data/mip_field_gnss_sbas_info.htm\n"
"\n"
"# Header containing common information\n"
"#   header.frame_id has no meaning in this message\n"
"microstrain_inertial_msgs/MipHeader header\n"
"\n"
"# GPS time of week (seconds)\n"
"float64 time_of_week\n"
"\n"
"# GPS weeks since 1980 (weeks)\n"
"uint16 week_number\n"
"\n"
"# SBAS system if. See SBAS_SYSTEM_* enums for possible values\n"
"uint8 sbas_system\n"
"\n"
"# SBAS satellite id\n"
"uint8 sbas_id\n"
"\n"
"# Number of SBAS corrections\n"
"uint8 count\n"
"\n"
"# Parsed out version of the SBAS status bitfield\n"
"microstrain_inertial_msgs/MipGnssSbasInfoSbasStatus sbas_status\n"
"\n"
"# Possible values for the sbas_system field\n"
"uint8 SBAS_SYSTEM_UNKNOWN = 0\n"
"uint8 SBAS_SYSTEM_WAAS    = 1\n"
"uint8 SBAS_SYSTEM_EGNOS   = 2\n"
"uint8 SBAS_SYSTEM_MSAS    = 3\n"
"uint8 SBAS_SYSTEM_GAGAN   = 4\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipHeader\n"
"# Represents a standard header that all MIP fields should include at the beginning of their message definition\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# Standard ROS header.\n"
"#   header.stamp will always be populated with the ROS time that this message was populated\n"
"#   header.frame_id is dependent on the full message definition. Most messages will not use this\n"
"std_msgs/Header header\n"
"\n"
"# If the message was triggered by an event, this will be set, otherwise it will be set to 0 (will be 0 most of the time)\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_event_source.htm\n"
"uint8 event_source\n"
"\n"
"# Reference timestamp of when the data was sampled if the device supports it. For devices that do not support this, it will always be 0\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_reference_timestamp.htm\n"
"uint64 reference_timestamp\n"
"\n"
"# GPS timestamp of when the data was sampled if the device supports it\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"# Note that this timestamp may be blank in certain messages, but there will often be equivalent fields in the messages\n"
"microstrain_inertial_msgs/MipGpsTimestamp gps_timestamp\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestamp\n"
"# Definition of a GPS timestamp.\n"
"# For more information see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# GPS time of week (seconds)\n"
"float64 tow\n"
"\n"
"# GPS Week number since 1980 (weeks)\n"
"uint16 week_number\n"
"\n"
"# Valid Flags bitfield\n"
"microstrain_inertial_msgs/MipGpsTimestampValidFlags valid_flags\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestampValidFlags\n"
"# Message definition for the valid_flags field of https://files.microstrain.com/CV7+Online/external_content/dcp/Data/0xff/data/0xd3.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"# Whole number seconds TOW has been set\n"
"bool tow\n"
"\n"
"# Week number has been set\n"
"bool week_number\n"
"\n"
"# Both TOW and Week Number have been set\n"
"bool time_valid\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGnssSbasInfoSbasStatus\n"
"# Message definition for the Sbas Status field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/data/mip_field_gnss_sbas_info.htm?Highlight=sbas%20info\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"bool range_available\n"
"bool corrections_available\n"
"bool integrity_available\n"
"bool test_mode\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_of_week);
      stream.next(m.week_number);
      stream.next(m.sbas_system);
      stream.next(m.sbas_id);
      stream.next(m.count);
      stream.next(m.sbas_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipGnssSbasInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipGnssSbasInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_of_week: ";
    Printer<double>::stream(s, indent + "  ", v.time_of_week);
    s << indent << "week_number: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.week_number);
    s << indent << "sbas_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sbas_system);
    s << indent << "sbas_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sbas_id);
    s << indent << "count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.count);
    s << indent << "sbas_status: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipGnssSbasInfoSbasStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.sbas_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSSBASINFO_H
