// Generated by gencpp from file microstrain_inertial_msgs/MipGnssCorrectionsRtkCorrectionsStatusDongleStatus.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSCORRECTIONSRTKCORRECTIONSSTATUSDONGLESTATUS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSCORRECTIONSRTKCORRECTIONSSTATUSDONGLESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_
{
  typedef MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> Type;

  MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_()
    : modem_state(0)
    , connection_type(0)
    , rssi(0)
    , signal_quality(0)
    , tower_change_indicator(0)
    , nmea_timeout_flag(false)
    , server_timeout_flag(false)
    , rtcm_timeout_flag(false)
    , device_out_of_range_flag(false)
    , corrections_unavailable_flag(false)  {
    }
  MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_(const ContainerAllocator& _alloc)
    : modem_state(0)
    , connection_type(0)
    , rssi(0)
    , signal_quality(0)
    , tower_change_indicator(0)
    , nmea_timeout_flag(false)
    , server_timeout_flag(false)
    , rtcm_timeout_flag(false)
    , device_out_of_range_flag(false)
    , corrections_unavailable_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _modem_state_type;
  _modem_state_type modem_state;

   typedef uint8_t _connection_type_type;
  _connection_type_type connection_type;

   typedef int8_t _rssi_type;
  _rssi_type rssi;

   typedef uint8_t _signal_quality_type;
  _signal_quality_type signal_quality;

   typedef uint8_t _tower_change_indicator_type;
  _tower_change_indicator_type tower_change_indicator;

   typedef uint8_t _nmea_timeout_flag_type;
  _nmea_timeout_flag_type nmea_timeout_flag;

   typedef uint8_t _server_timeout_flag_type;
  _server_timeout_flag_type server_timeout_flag;

   typedef uint8_t _rtcm_timeout_flag_type;
  _rtcm_timeout_flag_type rtcm_timeout_flag;

   typedef uint8_t _device_out_of_range_flag_type;
  _device_out_of_range_flag_type device_out_of_range_flag;

   typedef uint8_t _corrections_unavailable_flag_type;
  _corrections_unavailable_flag_type corrections_unavailable_flag;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODEM_STATE_OFF)
  #undef MODEM_STATE_OFF
#endif
#if defined(_WIN32) && defined(MODEM_STATE_NO_NETWORK)
  #undef MODEM_STATE_NO_NETWORK
#endif
#if defined(_WIN32) && defined(MODEM_STATE_NETWORK_CONNECTED)
  #undef MODEM_STATE_NETWORK_CONNECTED
#endif
#if defined(_WIN32) && defined(MODEM_STATE_CONFIGURING_DATA_CONTEXT)
  #undef MODEM_STATE_CONFIGURING_DATA_CONTEXT
#endif
#if defined(_WIN32) && defined(MODEM_STATE_ACTIVATING_DATA_CONTEXT)
  #undef MODEM_STATE_ACTIVATING_DATA_CONTEXT
#endif
#if defined(_WIN32) && defined(MODEM_STATE_CONFIGURING_SOCKET)
  #undef MODEM_STATE_CONFIGURING_SOCKET
#endif
#if defined(_WIN32) && defined(MODEM_STATE_WAITING_ON_SERVER_HANDSHAKE)
  #undef MODEM_STATE_WAITING_ON_SERVER_HANDSHAKE
#endif
#if defined(_WIN32) && defined(MODEM_STATE_CONNECTED_AND_IDLE)
  #undef MODEM_STATE_CONNECTED_AND_IDLE
#endif
#if defined(_WIN32) && defined(MODEM_STATE_CONNECTED_AND_STREAMING)
  #undef MODEM_STATE_CONNECTED_AND_STREAMING
#endif
#if defined(_WIN32) && defined(CONNECTION_TYPE_NO_CONNECTION)
  #undef CONNECTION_TYPE_NO_CONNECTION
#endif
#if defined(_WIN32) && defined(CONNECTION_TYPE_CONNECTION_2G)
  #undef CONNECTION_TYPE_CONNECTION_2G
#endif
#if defined(_WIN32) && defined(CONNECTION_TYPE_CONNECTION_3G)
  #undef CONNECTION_TYPE_CONNECTION_3G
#endif
#if defined(_WIN32) && defined(CONNECTION_TYPE_CONNECTION_4G)
  #undef CONNECTION_TYPE_CONNECTION_4G
#endif
#if defined(_WIN32) && defined(CONNECTION_TYPE_CONNECTION_5G)
  #undef CONNECTION_TYPE_CONNECTION_5G
#endif

  enum {
    MODEM_STATE_OFF = 0u,
    MODEM_STATE_NO_NETWORK = 1u,
    MODEM_STATE_NETWORK_CONNECTED = 2u,
    MODEM_STATE_CONFIGURING_DATA_CONTEXT = 3u,
    MODEM_STATE_ACTIVATING_DATA_CONTEXT = 4u,
    MODEM_STATE_CONFIGURING_SOCKET = 5u,
    MODEM_STATE_WAITING_ON_SERVER_HANDSHAKE = 6u,
    MODEM_STATE_CONNECTED_AND_IDLE = 7u,
    MODEM_STATE_CONNECTED_AND_STREAMING = 8u,
    CONNECTION_TYPE_NO_CONNECTION = 0u,
    CONNECTION_TYPE_CONNECTION_2G = 2u,
    CONNECTION_TYPE_CONNECTION_3G = 3u,
    CONNECTION_TYPE_CONNECTION_4G = 4u,
    CONNECTION_TYPE_CONNECTION_5G = 5u,
  };


  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_

typedef ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<std::allocator<void> > MipGnssCorrectionsRtkCorrectionsStatusDongleStatus;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus > MipGnssCorrectionsRtkCorrectionsStatusDongleStatusPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus const> MipGnssCorrectionsRtkCorrectionsStatusDongleStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator2> & rhs)
{
  return lhs.modem_state == rhs.modem_state &&
    lhs.connection_type == rhs.connection_type &&
    lhs.rssi == rhs.rssi &&
    lhs.signal_quality == rhs.signal_quality &&
    lhs.tower_change_indicator == rhs.tower_change_indicator &&
    lhs.nmea_timeout_flag == rhs.nmea_timeout_flag &&
    lhs.server_timeout_flag == rhs.server_timeout_flag &&
    lhs.rtcm_timeout_flag == rhs.rtcm_timeout_flag &&
    lhs.device_out_of_range_flag == rhs.device_out_of_range_flag &&
    lhs.corrections_unavailable_flag == rhs.corrections_unavailable_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6b32ecff25b8d73f86e7e5db3fce5f8";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6b32ecff25b8d73ULL;
  static const uint64_t static_value2 = 0xf86e7e5db3fce5f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipGnssCorrectionsRtkCorrectionsStatusDongleStatus";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the Dongle Status field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_corrections/data/mip_field_gnss_rtk_corrections_status.htm?Highlight=rtk%20status\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"# Modem State bits from the Dongle Status field. See MODEM_STATE_* enums for possible values\n"
"uint8 modem_state\n"
"\n"
"# Connection Type bits from the Dongle Status field. See CONNECTION_TYPE_* enums for possible values\n"
"uint8 connection_type\n"
"\n"
"# RSSI bits from the Dongle Status field. Units are in dBm\n"
"int8 rssi\n"
"\n"
"# Signal Quality bits from the Dongle Status field.\n"
"# 0-10 indication of signal quality, 0 means unavailable/invalid/not connected, 1 is poor, 10 is excellent.\n"
"uint8 signal_quality\n"
"\n"
"# Tower Change Indicator bits from the Dongle Status field.\n"
"# 4-bit value that increments each time a cell tower change occurs. Rolls over from 15 to 0.\n"
"uint8 tower_change_indicator\n"
"\n"
"# NMEA Timeout Flag bit from the Dongle Status field.\n"
"# The device has not received a valid NMEA message from the GQ7 in the past 3 seconds\n"
"bool nmea_timeout_flag\n"
"\n"
"# Server Timeout Flag bit from the Dongle Status field.\n"
"# The device has not received any communications with the server in the past 3 seconds.\n"
"bool server_timeout_flag\n"
"\n"
"# RTCM Timeout Flag bit from the Dongle Status field.\n"
"# The device has not received a valid RTCM message from the server in the past 3 seconds.\n"
"bool rtcm_timeout_flag\n"
"\n"
"# Device Out of Range Flag bit from the Dongle Status field\n"
"# The device's reported position is beyond the server-side configured distance to a base station and will not receive corrections\n"
"bool device_out_of_range_flag\n"
"\n"
"# Corrections Unavailable Flag bit from the Dongle Status field\n"
"# The server is reporting that corrections are not available given the user's account settings\n"
"bool corrections_unavailable_flag\n"
"\n"
"# Possible values for dongle_modem_state\n"
"uint8 MODEM_STATE_OFF = 0\n"
"uint8 MODEM_STATE_NO_NETWORK = 1\n"
"uint8 MODEM_STATE_NETWORK_CONNECTED = 2\n"
"uint8 MODEM_STATE_CONFIGURING_DATA_CONTEXT = 3\n"
"uint8 MODEM_STATE_ACTIVATING_DATA_CONTEXT = 4\n"
"uint8 MODEM_STATE_CONFIGURING_SOCKET = 5\n"
"uint8 MODEM_STATE_WAITING_ON_SERVER_HANDSHAKE = 6\n"
"uint8 MODEM_STATE_CONNECTED_AND_IDLE = 7\n"
"uint8 MODEM_STATE_CONNECTED_AND_STREAMING = 8\n"
"\n"
"# Possible values for dongle_connection_type\n"
"uint8 CONNECTION_TYPE_NO_CONNECTION = 0\n"
"uint8 CONNECTION_TYPE_CONNECTION_2G = 2\n"
"uint8 CONNECTION_TYPE_CONNECTION_3G = 3\n"
"uint8 CONNECTION_TYPE_CONNECTION_4G = 4\n"
"uint8 CONNECTION_TYPE_CONNECTION_5G = 5\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.modem_state);
      stream.next(m.connection_type);
      stream.next(m.rssi);
      stream.next(m.signal_quality);
      stream.next(m.tower_change_indicator);
      stream.next(m.nmea_timeout_flag);
      stream.next(m.server_timeout_flag);
      stream.next(m.rtcm_timeout_flag);
      stream.next(m.device_out_of_range_flag);
      stream.next(m.corrections_unavailable_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipGnssCorrectionsRtkCorrectionsStatusDongleStatus_<ContainerAllocator>& v)
  {
    s << indent << "modem_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.modem_state);
    s << indent << "connection_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connection_type);
    s << indent << "rssi: ";
    Printer<int8_t>::stream(s, indent + "  ", v.rssi);
    s << indent << "signal_quality: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.signal_quality);
    s << indent << "tower_change_indicator: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tower_change_indicator);
    s << indent << "nmea_timeout_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nmea_timeout_flag);
    s << indent << "server_timeout_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.server_timeout_flag);
    s << indent << "rtcm_timeout_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rtcm_timeout_flag);
    s << indent << "device_out_of_range_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.device_out_of_range_flag);
    s << indent << "corrections_unavailable_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.corrections_unavailable_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPGNSSCORRECTIONSRTKCORRECTIONSSTATUSDONGLESTATUS_H
