// Generated by gencpp from file microstrain_inertial_msgs/MipSensorOverrangeStatusStatus.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPSENSOROVERRANGESTATUSSTATUS_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPSENSOROVERRANGESTATUSSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipSensorOverrangeStatusStatus_
{
  typedef MipSensorOverrangeStatusStatus_<ContainerAllocator> Type;

  MipSensorOverrangeStatusStatus_()
    : accel_x(false)
    , accel_y(false)
    , accel_z(false)
    , gyro_x(false)
    , gyro_y(false)
    , gyro_z(false)
    , mag_x(false)
    , mag_y(false)
    , mag_z(false)
    , press(false)  {
    }
  MipSensorOverrangeStatusStatus_(const ContainerAllocator& _alloc)
    : accel_x(false)
    , accel_y(false)
    , accel_z(false)
    , gyro_x(false)
    , gyro_y(false)
    , gyro_z(false)
    , mag_x(false)
    , mag_y(false)
    , mag_z(false)
    , press(false)  {
  (void)_alloc;
    }



   typedef uint8_t _accel_x_type;
  _accel_x_type accel_x;

   typedef uint8_t _accel_y_type;
  _accel_y_type accel_y;

   typedef uint8_t _accel_z_type;
  _accel_z_type accel_z;

   typedef uint8_t _gyro_x_type;
  _gyro_x_type gyro_x;

   typedef uint8_t _gyro_y_type;
  _gyro_y_type gyro_y;

   typedef uint8_t _gyro_z_type;
  _gyro_z_type gyro_z;

   typedef uint8_t _mag_x_type;
  _mag_x_type mag_x;

   typedef uint8_t _mag_y_type;
  _mag_y_type mag_y;

   typedef uint8_t _mag_z_type;
  _mag_z_type mag_z;

   typedef uint8_t _press_type;
  _press_type press;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MipSensorOverrangeStatusStatus_

typedef ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<std::allocator<void> > MipSensorOverrangeStatusStatus;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus > MipSensorOverrangeStatusStatusPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus const> MipSensorOverrangeStatusStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator2> & rhs)
{
  return lhs.accel_x == rhs.accel_x &&
    lhs.accel_y == rhs.accel_y &&
    lhs.accel_z == rhs.accel_z &&
    lhs.gyro_x == rhs.gyro_x &&
    lhs.gyro_y == rhs.gyro_y &&
    lhs.gyro_z == rhs.gyro_z &&
    lhs.mag_x == rhs.mag_x &&
    lhs.mag_y == rhs.mag_y &&
    lhs.mag_z == rhs.mag_z &&
    lhs.press == rhs.press;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b343e6367e45b73c841c8255a4cfbba";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b343e6367e45b73ULL;
  static const uint64_t static_value2 = 0xc841c8255a4cfbbaULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipSensorOverrangeStatusStatus";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the Status field of https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/sensor_data/data/mip_field_sensor_overrange_status.htm?Highlight=overrange\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"bool accel_x\n"
"bool accel_y\n"
"bool accel_z\n"
"bool gyro_x\n"
"bool gyro_y\n"
"bool gyro_z\n"
"bool mag_x\n"
"bool mag_y\n"
"bool mag_z\n"
"bool press\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accel_x);
      stream.next(m.accel_y);
      stream.next(m.accel_z);
      stream.next(m.gyro_x);
      stream.next(m.gyro_y);
      stream.next(m.gyro_z);
      stream.next(m.mag_x);
      stream.next(m.mag_y);
      stream.next(m.mag_z);
      stream.next(m.press);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipSensorOverrangeStatusStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipSensorOverrangeStatusStatus_<ContainerAllocator>& v)
  {
    s << indent << "accel_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accel_x);
    s << indent << "accel_y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accel_y);
    s << indent << "accel_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accel_z);
    s << indent << "gyro_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gyro_x);
    s << indent << "gyro_y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gyro_y);
    s << indent << "gyro_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gyro_z);
    s << indent << "mag_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mag_x);
    s << indent << "mag_y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mag_y);
    s << indent << "mag_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mag_z);
    s << indent << "press: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.press);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPSENSOROVERRANGESTATUSSTATUS_H
