// Generated by gencpp from file microstrain_inertial_msgs/MipSystemBuiltInTest.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPSYSTEMBUILTINTEST_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPSYSTEMBUILTINTEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <microstrain_inertial_msgs/MipHeader.h>

namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct MipSystemBuiltInTest_
{
  typedef MipSystemBuiltInTest_<ContainerAllocator> Type;

  MipSystemBuiltInTest_()
    : header()
    , result()  {
      result.assign(0);
  }
  MipSystemBuiltInTest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , result()  {
  (void)_alloc;
      result.assign(0);
  }



   typedef  ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint8_t, 16>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> const> ConstPtr;

}; // struct MipSystemBuiltInTest_

typedef ::microstrain_inertial_msgs::MipSystemBuiltInTest_<std::allocator<void> > MipSystemBuiltInTest;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSystemBuiltInTest > MipSystemBuiltInTestPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::MipSystemBuiltInTest const> MipSystemBuiltInTestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e13c333180f60180b5dea5b7141b9f3";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e13c333180f6018ULL;
  static const uint64_t static_value2 = 0x0b5dea5b7141b9f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/MipSystemBuiltInTest";
  }

  static const char* value(const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message definition for the MIP field https://files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/0xa0/data/0x01.htm\n"
"\n"
"# Header containing common information\n"
"#   header.frame_id has no meaning in this message\n"
"microstrain_inertial_msgs/MipHeader header\n"
"\n"
"# Device-specific bitfield (128 bits).\n"
"# See device user manual.\n"
"# Bits are least-significant-byte first.\n"
"# For example, bit 0 is located at bit 0 of result[0], bit 1 is located at bit 1 of result[0], bit 8 is located at bit 0 of result[1], and bit 127 is located at bit 7 of result[15].\n"
"uint8[16] result\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipHeader\n"
"# Represents a standard header that all MIP fields should include at the beginning of their message definition\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# Standard ROS header.\n"
"#   header.stamp will always be populated with the ROS time that this message was populated\n"
"#   header.frame_id is dependent on the full message definition. Most messages will not use this\n"
"std_msgs/Header header\n"
"\n"
"# If the message was triggered by an event, this will be set, otherwise it will be set to 0 (will be 0 most of the time)\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_event_source.htm\n"
"uint8 event_source\n"
"\n"
"# Reference timestamp of when the data was sampled if the device supports it. For devices that do not support this, it will always be 0\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_reference_timestamp.htm\n"
"uint64 reference_timestamp\n"
"\n"
"# GPS timestamp of when the data was sampled if the device supports it\n"
"# For more information, see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"# Note that this timestamp may be blank in certain messages, but there will often be equivalent fields in the messages\n"
"microstrain_inertial_msgs/MipGpsTimestamp gps_timestamp\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestamp\n"
"# Definition of a GPS timestamp.\n"
"# For more information see: https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/shared_data/data/mip_field_shared_gps_timestamp.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages\n"
"\n"
"# GPS time of week (seconds)\n"
"float64 tow\n"
"\n"
"# GPS Week number since 1980 (weeks)\n"
"uint16 week_number\n"
"\n"
"# Valid Flags bitfield\n"
"microstrain_inertial_msgs/MipGpsTimestampValidFlags valid_flags\n"
"================================================================================\n"
"MSG: microstrain_inertial_msgs/MipGpsTimestampValidFlags\n"
"# Message definition for the valid_flags field of https://files.microstrain.com/CV7+Online/external_content/dcp/Data/0xff/data/0xd3.htm\n"
"#   Note: This message will never be published on it's own, only included in other messages.\n"
"\n"
"# Whole number seconds TOW has been set\n"
"bool tow\n"
"\n"
"# Week number has been set\n"
"bool week_number\n"
"\n"
"# Both TOW and Week Number have been set\n"
"bool time_valid\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MipSystemBuiltInTest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::MipSystemBuiltInTest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::microstrain_inertial_msgs::MipHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_MIPSYSTEMBUILTINTEST_H
