// Generated by gencpp from file microstrain_inertial_msgs/RawFileConfigWrite.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_RAWFILECONFIGWRITE_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_RAWFILECONFIGWRITE_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/RawFileConfigWriteRequest.h>
#include <microstrain_inertial_msgs/RawFileConfigWriteResponse.h>


namespace microstrain_inertial_msgs
{

struct RawFileConfigWrite
{

typedef RawFileConfigWriteRequest Request;
typedef RawFileConfigWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RawFileConfigWrite
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWrite > {
  static const char* value()
  {
    return "1983e7091dff1eb83e867fcdf514855d";
  }

  static const char* value(const ::microstrain_inertial_msgs::RawFileConfigWrite&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::RawFileConfigWrite > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/RawFileConfigWrite";
  }

  static const char* value(const ::microstrain_inertial_msgs::RawFileConfigWrite&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWriteRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWrite >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWrite >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::RawFileConfigWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::RawFileConfigWriteRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::RawFileConfigWrite >
template<>
struct DataType< ::microstrain_inertial_msgs::RawFileConfigWriteRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::RawFileConfigWrite >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::RawFileConfigWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWriteResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWrite >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::RawFileConfigWrite >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::RawFileConfigWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::RawFileConfigWriteResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::RawFileConfigWrite >
template<>
struct DataType< ::microstrain_inertial_msgs::RawFileConfigWriteResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::RawFileConfigWrite >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::RawFileConfigWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_RAWFILECONFIGWRITE_H
