# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from microstrain_inertial_msgs/MipGnssSbasInfoSbasStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MipGnssSbasInfoSbasStatus(genpy.Message):
  _md5sum = "d44b1dcf4b6c5470a42c909b93caefc4"
  _type = "microstrain_inertial_msgs/MipGnssSbasInfoSbasStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Message definition for the Sbas Status field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/data/mip_field_gnss_sbas_info.htm?Highlight=sbas%20info
#   Note: This message will never be published on it's own, only included in other messages.

bool range_available
bool corrections_available
bool integrity_available
bool test_mode"""
  __slots__ = ['range_available','corrections_available','integrity_available','test_mode']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       range_available,corrections_available,integrity_available,test_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MipGnssSbasInfoSbasStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.range_available is None:
        self.range_available = False
      if self.corrections_available is None:
        self.corrections_available = False
      if self.integrity_available is None:
        self.integrity_available = False
      if self.test_mode is None:
        self.test_mode = False
    else:
      self.range_available = False
      self.corrections_available = False
      self.integrity_available = False
      self.test_mode = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.range_available, _x.corrections_available, _x.integrity_available, _x.test_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.range_available, _x.corrections_available, _x.integrity_available, _x.test_mode,) = _get_struct_4B().unpack(str[start:end])
      self.range_available = bool(self.range_available)
      self.corrections_available = bool(self.corrections_available)
      self.integrity_available = bool(self.integrity_available)
      self.test_mode = bool(self.test_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.range_available, _x.corrections_available, _x.integrity_available, _x.test_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.range_available, _x.corrections_available, _x.integrity_available, _x.test_mode,) = _get_struct_4B().unpack(str[start:end])
      self.range_available = bool(self.range_available)
      self.corrections_available = bool(self.corrections_available)
      self.integrity_available = bool(self.integrity_available)
      self.test_mode = bool(self.test_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
