# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from microstrain_inertial_msgs/MipFilterGnssDualAntennaStatusStatusFlags.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MipFilterGnssDualAntennaStatusStatusFlags(genpy.Message):
  _md5sum = "606778f7e3bc3fceb7877383568e2671"
  _type = "microstrain_inertial_msgs/MipFilterGnssDualAntennaStatusStatusFlags"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Message definition for Status Flags field of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/filter_data/data/mip_field_filter_gnss_dual_antenna_status.htm?Highlight=dual%20antenna
#   Note: This message will never be published on it's own, only included in other messages.

bool rcv_1_data_valid
bool rcv_2_data_valid
bool antenna_offsets_valid"""
  __slots__ = ['rcv_1_data_valid','rcv_2_data_valid','antenna_offsets_valid']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rcv_1_data_valid,rcv_2_data_valid,antenna_offsets_valid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MipFilterGnssDualAntennaStatusStatusFlags, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rcv_1_data_valid is None:
        self.rcv_1_data_valid = False
      if self.rcv_2_data_valid is None:
        self.rcv_2_data_valid = False
      if self.antenna_offsets_valid is None:
        self.antenna_offsets_valid = False
    else:
      self.rcv_1_data_valid = False
      self.rcv_2_data_valid = False
      self.antenna_offsets_valid = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.rcv_1_data_valid, _x.rcv_2_data_valid, _x.antenna_offsets_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.rcv_1_data_valid, _x.rcv_2_data_valid, _x.antenna_offsets_valid,) = _get_struct_3B().unpack(str[start:end])
      self.rcv_1_data_valid = bool(self.rcv_1_data_valid)
      self.rcv_2_data_valid = bool(self.rcv_2_data_valid)
      self.antenna_offsets_valid = bool(self.antenna_offsets_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.rcv_1_data_valid, _x.rcv_2_data_valid, _x.antenna_offsets_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.rcv_1_data_valid, _x.rcv_2_data_valid, _x.antenna_offsets_valid,) = _get_struct_3B().unpack(str[start:end])
      self.rcv_1_data_valid = bool(self.rcv_1_data_valid)
      self.rcv_2_data_valid = bool(self.rcv_2_data_valid)
      self.antenna_offsets_valid = bool(self.antenna_offsets_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
