# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ouster_ros/Telemetry.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Telemetry(genpy.Message):
  _md5sum = "41824d1195ebb9ac184e7c24e9f33bfa"
  _type = "ouster_ros/Telemetry"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# This message defines the telemetry data for Ouster sensors.

# ThermalShutdownStatus thermal_shutdown
uint8 THERMAL_SHUTDOWN_NORMAL=0    # Normal operation
uint8 THERMAL_SHUTDOWN_IMMINENT=1  # Thermal Shutdown imminent

# ShotLimitingStatus shot_limiting
uint8 SHOT_LIMITING_NORMAL=0          # Normal operation
uint8 SHOT_LIMITING_IMMINENT=1        # Shot limiting imminent
uint8 SHOT_LIMITING_REDUCTION_0_10=2  # Shot limiting reduction by 0 to 10%
uint8 SHOT_LIMITING_REDUCTION_10_20=3 # Shot limiting reduction by 10 to 20%
uint8 SHOT_LIMITING_REDUCTION_20_30=4 # Shot limiting reduction by 20 to 30%
uint8 SHOT_LIMITING_REDUCTION_30_40=5 # Shot limiting reduction by 30 to 40%
uint8 SHOT_LIMITING_REDUCTION_40_50=6 # Shot limiting reduction by 40 to 50%
uint8 SHOT_LIMITING_REDUCTION_50_60=7 # Shot limiting reduction by 50 to 60%
uint8 SHOT_LIMITING_REDUCTION_60_70=8 # Shot limiting reduction by 60 to 70%
uint8 SHOT_LIMITING_REDUCTION_70_75=9 # Shot limiting reduction by 70 to 80%

# Message header
std_msgs/Header header
# Telemetry fields for more information on these fields and their meaning, please review:
# https://static.ouster.dev/sensor-docs/image_route1/image_route2/thermal_int_guide/therm_int_guide.html
uint16 countdown_thermal_shutdown # the thermal shutdown countdown.
uint16 countdown_shot_limiting    # the shot limiting countdown.
uint8 thermal_shutdown            # the thermal shutdown status. 0 = NORMAL, 1 = SHUTDOWN IMMINENT.
uint8 shot_limiting               # the shot limiting status. 0 = NORMAL OPERATION.

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  THERMAL_SHUTDOWN_NORMAL = 0
  THERMAL_SHUTDOWN_IMMINENT = 1
  SHOT_LIMITING_NORMAL = 0
  SHOT_LIMITING_IMMINENT = 1
  SHOT_LIMITING_REDUCTION_0_10 = 2
  SHOT_LIMITING_REDUCTION_10_20 = 3
  SHOT_LIMITING_REDUCTION_20_30 = 4
  SHOT_LIMITING_REDUCTION_30_40 = 5
  SHOT_LIMITING_REDUCTION_40_50 = 6
  SHOT_LIMITING_REDUCTION_50_60 = 7
  SHOT_LIMITING_REDUCTION_60_70 = 8
  SHOT_LIMITING_REDUCTION_70_75 = 9

  __slots__ = ['header','countdown_thermal_shutdown','countdown_shot_limiting','thermal_shutdown','shot_limiting']
  _slot_types = ['std_msgs/Header','uint16','uint16','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,countdown_thermal_shutdown,countdown_shot_limiting,thermal_shutdown,shot_limiting

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Telemetry, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.countdown_thermal_shutdown is None:
        self.countdown_thermal_shutdown = 0
      if self.countdown_shot_limiting is None:
        self.countdown_shot_limiting = 0
      if self.thermal_shutdown is None:
        self.thermal_shutdown = 0
      if self.shot_limiting is None:
        self.shot_limiting = 0
    else:
      self.header = std_msgs.msg.Header()
      self.countdown_thermal_shutdown = 0
      self.countdown_shot_limiting = 0
      self.thermal_shutdown = 0
      self.shot_limiting = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2H2B().pack(_x.countdown_thermal_shutdown, _x.countdown_shot_limiting, _x.thermal_shutdown, _x.shot_limiting))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.countdown_thermal_shutdown, _x.countdown_shot_limiting, _x.thermal_shutdown, _x.shot_limiting,) = _get_struct_2H2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2H2B().pack(_x.countdown_thermal_shutdown, _x.countdown_shot_limiting, _x.thermal_shutdown, _x.shot_limiting))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.countdown_thermal_shutdown, _x.countdown_shot_limiting, _x.thermal_shutdown, _x.shot_limiting,) = _get_struct_2H2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H2B = None
def _get_struct_2H2B():
    global _struct_2H2B
    if _struct_2H2B is None:
        _struct_2H2B = struct.Struct("<2H2B")
    return _struct_2H2B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
